  // Your use of the content in the files referenced here is subject to the terms of the license at https://aka.ms/fabric-assets-license

// tslint:disable:max-line-length

import {
  IIconOptions,
  IIconSubset,
  registerIcons
} from '@uifabric/styling';

export function initializeIcons(
  baseUrl: string = '',
  options?: IIconOptions
): void {
  const subset: IIconSubset = {
    style: {
      MozOsxFontSmoothing: 'grayscale',
      WebkitFontSmoothing: 'antialiased',
      fontStyle: 'normal',
      fontWeight: 'normal',
      speak: 'none'
    },
    fontFace: {
      fontFamily: `"FabricMDL2Icons-6"`,
      src: `url('${baseUrl}fabric-icons-6-0aefebc6.woff') format('woff')`
    },
    icons: {
      'DataFilter': '\uE68A',
      'DataFlow': '\uE577',
      'Dataflows': '\uF7DD',
      'DataflowsLink': '\uE366',
      'DataManagementSettings': '\uEFC8',
      'DatamartExternal': '\uE69B',
      'Dataverse': '\uE659',
      'DateTime': '\uEC92',
      'DateTime12': '\uF38F',
      'DateTime2': '\uEA17',
      'DateTimeMirrored': '\uEE93',
      'DeactivateOrders': '\uEFE1',
      'Debug': '\uF395',
      'DebugAll': '\uF398',
      'Decimals': '\uF218',
      'DecisionSolid': '\uF350',
      'DeclineCall': '\uF405',
      'DecreaseIndent': '\uE39B',
      'DecreaseIndentArrow': '\uF7A3',
      'DecreaseIndentArrowMirrored': '\uF7A7',
      'DecreaseIndentMirrored': '\uE39C',
      'DecreaseIndentText': '\uF7A2',
      'DecreaseIndentTextMirrored': '\uF7A6',
      'DefaultRatio': '\uF529',
      'DefaultSettings': '\uF648',
      'DefectSolid': '\uF449',
      'DefenderApp': '\uE83D',
      'DefenderBadge12': '\uF0FB',
      'DefenderTVM': '\uF6B3',
      'Delete': '\uE74D',
      'DeleteColumns': '\uF64E',
      'DeleteRows': '\uF64F',
      'DeleteRowsMirrored': '\uF650',
      'DeleteTable': '\uF651',
      'DeliveryTruck': '\uEBF4',
      'DelveAnalytics': '\uEEEE',
      'DelveAnalyticsLogo': '\uEDCA',
      'DelveLogo': '\uF280',
      'DelveLogoFill': '\uF281',
      'DelveLogoInverse': '\uED76',
      'DensityComfy': '\uE4BA',
      'DensityDefault': '\uE4B9',
      'DependencyAdd': '\uE344',
      'DependencyRemove': '\uE345',
      'Deploy': '\uF29D',
      'Descending': '\uEDC1',
      'Design': '\uEB3C',
      'DesktopFlow': '\uE4F3',
      'DesktopScreenshot': '\uF5D9',
      'DeveloperTools': '\uEC7A',
      'DeviceBug': '\uE424',
      'DeviceOff': '\uE402',
      'DeviceRun': '\uE401',
      'Devices2': '\uE975',
      'Devices3': '\uEA6C',
      'Devices4': '\uEB66',
      'Diagnostic': '\uE9D9',
      'DiagnosticDataBar': '\uF633',
      'DiagnosticDataBarTooltip': '\uF7DF',
      'DiagnosticDataViewerApp': '\uF568',
      'Dialpad': '\uE75F',
      'DialShape1': '\uF156',
      'DialShape3': '\uF158',
      'Diamond': '\uED02',
      'DiamondSolid': '\uF34C',
      'DiamondUser': '\uE4F9',
      'Dictionary': '\uE82D',
      'DictionaryRemove': '\uF69A',
      'DietPlanNotebook': '\uEAC8',
      'DiffInline': '\uF309',
      'DiffSideBySide': '\uF30A',
      'Diploma': '\uF320',
      'DisableUpdates': '\uE8D8',
      'DisconnectVirtualMachine': '\uF873',
      'Dislike': '\uE8E0',
      'DislikeSolid': '\uF3C0',
      'Distance': '\uECAE',
      'DistributeDown': '\uF76A',
      'DockLeft': '\uE90C',
      'DockLeftMirrored': '\uEA4C',
      'DockRight': '\uE90D',
      'DocLibrary': '\uEEB8',
      'DocsLogoInverse': '\uEDCB',
      'Document': '\uE8A5',
      'DocumentApproval': '\uF28B',
      'Documentation': '\uEC17',
      'DocumentManagement': '\uEFFC',
      'DocumentReply': '\uEF57',
      'DocumentSearch': '\uEF6C',
      'DocumentSet': '\uEED6',
      'DOM': '\uEC8D',
      'DonutChart': '\uF368',
      'Door': '\uEB75',
      'DoubleBookmark': '\uEB8F',
      'DoubleChevronDown': '\uEE04',
      'DoubleChevronDown12': '\uEE97',
      'DoubleChevronDown8': '\uF36B',
      'DoubleChevronLeft': '\uEDBE',
      'DoubleChevronLeft12': '\uEE98',
      'DoubleChevronLeft8': '\uF36D'
    }
  };

  registerIcons(subset, options);
}
