  // Your use of the content in the files referenced here is subject to the terms of the license at https://aka.ms/fabric-assets-license

// tslint:disable:max-line-length

import {
  IIconOptions,
  IIconSubset,
  registerIcons
} from '@uifabric/styling';

export function initializeIcons(
  baseUrl: string = '',
  options?: IIconOptions
): void {
  const subset: IIconSubset = {
    style: {
      MozOsxFontSmoothing: 'grayscale',
      WebkitFontSmoothing: 'antialiased',
      fontStyle: 'normal',
      fontWeight: 'normal',
      speak: 'none'
    },
    fontFace: {
      fontFamily: `"FabricMDL2Icons-22"`,
      src: `url('${baseUrl}fabric-icons-22-8da0885d.woff') format('woff')`
    },
    icons: {
      'Variable3': '\uE4D1',
      'VariableGroup': '\uF31B',
      'VB': '\uF2F2',
      'VennDiagram': '\uF273',
      'VerifiedBrand': '\uF7BD',
      'VerifiedBrandSolid': '\uF6AD',
      'VersionControlPush': '\uF664',
      'VerticalDistributeCenter': '\uF4FA',
      'Video': '\uE714',
      'Video360Generic': '\uF609',
      'VideoAdd': '\uE430',
      'VideoLightOff': '\uEA74',
      'VideoOff': '\uF4B0',
      'VideoOff2': '\uE43C',
      'VideoSearch': '\uF4EA',
      'VideoSolid': '\uEA0C',
      'View': '\uE890',
      'ViewAll': '\uE8A9',
      'ViewAll2': '\uEF56',
      'ViewDashboard': '\uF246',
      'ViewInAR': '\uE41F',
      'ViewList': '\uF247',
      'ViewListGroup': '\uF248',
      'ViewListTree': '\uF249',
      'ViewOriginal': '\uE7B4',
      'VirtualNetwork': '\uF815',
      'VisioDiagram': '\uF2A0',
      'VisioDiagramSync': '\uF762',
      'VisioDocument': '\uF2A9',
      'VisioLogo': '\uF2A7',
      'VisioLogo16': '\uF3A3',
      'VisioLogoInverse': '\uED7D',
      'VisioLogoInverse16': '\uF3A2',
      'VisualBasicLanguage': '\uF2F1',
      'VisuallyImpaired': '\uF866',
      'VisualsFolder': '\uF520',
      'VisualsStore': '\uF521',
      'VisualStudioForWindows': '\uF5D0',
      'VisualStudioForWindowsAlt': '\uEC22',
      'VivaTopicApp': '\uE687',
      'VoicemailForward': '\uED87',
      'VoicemailIRM': '\uF421',
      'VoicemailReply': '\uED88',
      'Volume0': '\uE992',
      'Volume1': '\uE993',
      'Volume2': '\uE994',
      'Volume3': '\uE995',
      'VolumeDisabled': '\uEA85',
      'VSTSAltLogo1': '\uF382',
      'VSTSAltLogo2': '\uF383',
      'VSTSLogo': '\uF381',
      'Waffle': '\uED89',
      'WaffleOffice365': '\uF4E0',
      'WaitlistConfirm': '\uF550',
      'WaitlistConfirmMirrored': '\uF551',
      'Warning': '\uE7BA',
      'Warning12': '\uF62F',
      'WarningSolid': '\uF736',
      'WavingHand': '\uF807',
      'WebAppBuilderFragment': '\uE314',
      'WebAppBuilderFragmentCreate': '\uE31B',
      'WebAppBuilderFragmentLock': '\uE4DD',
      'WebAppBuilderFragmentTest': '\uE4DE',
      'WebAppBuilderModule': '\uE313',
      'WebAppBuilderModuleLock': '\uE4DF',
      'WebAppBuilderModuleTest': '\uE4E0',
      'WebAppBuilderSlot': '\uE315',
      'Webcam2': '\uE960',
      'Webcam2Off': '\uE36D',
      'WebComponents': '\uEC8B',
      'WebEnvironment': '\uE3DB',
      'WebPublish': '\uF52F',
      'WebSearch': '\uF6FA',
      'Website': '\uEB41',
      'WebTemplate': '\uF6B2',
      'Weights': '\uEADB',
      'Wheelchair': '\uF31F',
      'Whiteboard': '\uF784',
      'WhiteBoardApp16': '\uF673',
      'WhiteBoardApp32': '\uF674',
      'WifiEthernet': '\uEE77',
      'WifiWarning4': '\uEB63',
      'WindDirection': '\uEBE6',
      'WindowEdit': '\uF50E',
      'WindowsLogo': '\uE782',
      'Wines': '\uEABF',
      'WipePhone': '\uED8D',
      'WordDocument': '\uEF71',
      'WordLogo': '\uF1E3',
      'WordLogo16': '\uF391',
      'WordLogoInverse': '\uEC29',
      'WordLogoInverse16': '\uF390',
      'Work': '\uE821',
      'WorkFlow': '\uEA01',
      'WorkforceManagement': '\uEE0F',
      'WorkItem': '\uF314',
      'WorkItemAlert': '\uF78F',
      'WorkItemBar': '\uF35C',
      'WorkItemBarSolid': '\uF35D',
      'WorkItemBug': '\uF315'
    }
  };

  registerIcons(subset, options);
}
