  // Your use of the content in the files referenced here is subject to the terms of the license at https://aka.ms/fabric-assets-license

// tslint:disable:max-line-length

import {
  IIconOptions,
  IIconSubset,
  registerIcons
} from '@uifabric/styling';

export function initializeIcons(
  baseUrl: string = '',
  options?: IIconOptions
): void {
  const subset: IIconSubset = {
    style: {
      MozOsxFontSmoothing: 'grayscale',
      WebkitFontSmoothing: 'antialiased',
      fontStyle: 'normal',
      fontWeight: 'normal',
      speak: 'none'
    },
    fontFace: {
      fontFamily: `"FabricMDL2Icons-21"`,
      src: `url('${baseUrl}fabric-icons-21-9afe3665.woff') format('woff')`
    },
    icons: {
      'Touch': '\uE815',
      'TouchPointer': '\uE7C9',
      'Trackers': '\uEADF',
      'TrackersMirrored': '\uEE92',
      'Train': '\uE7C0',
      'TrainSolid': '\uEB4D',
      'TransferCall': '\uED95',
      'Transition': '\uF3BC',
      'TransitionEffect': '\uF5B4',
      'TransitionPop': '\uF5B2',
      'TransitionPush': '\uF5B3',
      'Translate': '\uE7B2',
      'Transportation': '\uEBF1',
      'Trending12': '\uF62D',
      'TriangleDown12': '\uEED1',
      'TriangleLeft12': '\uEED2',
      'TriangleRight12': '\uEED3',
      'TriangleShape': '\uF1A7',
      'TriangleShapeSolid': '\uF63E',
      'TriangleSolid': '\uEA08',
      'TriangleSolidDown12': '\uEECD',
      'TriangleSolidLeft12': '\uEECE',
      'TriangleSolidRight12': '\uEECF',
      'TriangleSolidUp12': '\uEECC',
      'TriangleUp12': '\uEED0',
      'TriggerApproval': '\uF3B2',
      'TriggerAuto': '\uF24A',
      'TriggerPhrase': '\uE5FF',
      'TriggerUser': '\uF24B',
      'Trim': '\uE78A',
      'TrimEnd': '\uF8BC',
      'TrimStart': '\uF8BB',
      'TripleColumn': '\uF1D5',
      'TripleColumnEdit': '\uF323',
      'TripleColumnWide': '\uF66E',
      'Trophy': '\uED3F',
      'Trophy2': '\uF1AE',
      'Trophy2Solid': '\uF337',
      'TurnRight': '\uE7DB',
      'TurnUserLeft': '\uF269',
      'TVMonitor': '\uE7F4',
      'TVMonitorSelected': '\uEC77',
      'TypeScriptLanguage': '\uF2F7',
      'Umbrella': '\uEC04',
      'UnavailableOffline': '\uE545',
      'Underline': '\uE8DC',
      'UnderlineA': '\uE5CC',
      'UnderlineKorean': '\uE5BB',
      'UnderlineP': '\uE5CD',
      'UnderlineRussian': '\uE5B8',
      'UnderlineS': '\uE5B4',
      'UnderlineSerbian': '\uE5CB',
      'Undo': '\uE7A7',
      'Uneditable': '\uED1D',
      'Uneditable2': '\uF876',
      'Uneditable2Mirrored': '\uF877',
      'UneditableMirrored': '\uF4B9',
      'UneditableSolid12': '\uF4B7',
      'UneditableSolidMirrored12': '\uF4B8',
      'Unfavorite': '\uE8D9',
      'UngroupObject': '\uF4F2',
      'UniteShape': '\uF8FB',
      'Unknown': '\uE9CE',
      'UnknownCall': '\uED97',
      'UnknownMirrored': '\uF22E',
      'UnknownMirroredSolid': '\uF2E2',
      'UnknownSolid': '\uF2E1',
      'Unlock': '\uE785',
      'UnlockSolid': '\uF304',
      'Unpin': '\uE77A',
      'UnpublishContent': '\uE31F',
      'UnSetColor': '\uF3F9',
      'UnstackSelected': '\uE7FE',
      'Unsubscribe': '\uEDA0',
      'UnsyncFolder': '\uE8F6',
      'UnsyncOccurence': '\uF4A4',
      'Untag': '\uF60B',
      'Up': '\uE74A',
      'UpdateRestore': '\uE777',
      'UpgradeAnalysis': '\uEA0B',
      'UpKey': '\uF3E0',
      'Upload': '\uE898',
      'UpperCase': '\uE5ED',
      'URLBlock': '\uE3FE',
      'USB': '\uE88E',
      'UserClapper': '\uE666',
      'UserEvent': '\uF69C',
      'UserFollowed': '\uF25C',
      'UserGauge': '\uF6ED',
      'UserOptional': '\uF767',
      'UserPause': '\uF2BA',
      'UserRemove': '\uF69B',
      'UserSync': '\uF2B9',
      'UserWarning': '\uE368',
      'UserWindow': '\uE4ED',
      'Vacation': '\uF49F',
      'Vaccination': '\uEAE0',
      'VaccinationRecent': '\uE550',
      'Variable': '\uF305',
      'Variable2': '\uF86D'
    }
  };

  registerIcons(subset, options);
}
