  // Your use of the content in the files referenced here is subject to the terms of the license at https://aka.ms/fabric-assets-license

// tslint:disable:max-line-length

import {
  IIconOptions,
  IIconSubset,
  registerIcons
} from '@uifabric/styling';

export function initializeIcons(
  baseUrl: string = '',
  options?: IIconOptions
): void {
  const subset: IIconSubset = {
    style: {
      MozOsxFontSmoothing: 'grayscale',
      WebkitFontSmoothing: 'antialiased',
      fontStyle: 'normal',
      fontWeight: 'normal',
      speak: 'none'
    },
    fontFace: {
      fontFamily: `"FabricMDL2Icons-10"`,
      src: `url('${baseUrl}fabric-icons-10-36b68c83.woff') format('woff')`
    },
    icons: {
      'HailDay': '\uEA00',
      'HailNight': '\uEA13',
      'HalfAlpha': '\uE97E',
      'HalfCircle': '\uF501',
      'HandsFree': '\uEAD0',
      'Handwriting': '\uE929',
      'HardDrive': '\uEDA2',
      'HardDriveGroup': '\uF18F',
      'HardDriveLock': '\uF55A',
      'HardDriveUnlock': '\uF55B',
      'HazyDay': '\uE46B',
      'HazyNight': '\uE479',
      'Header': '\uF82F',
      'Header1': '\uEA19',
      'Header2': '\uEF36',
      'Header3': '\uEF37',
      'Header4': '\uEF38',
      'Headset': '\uE95B',
      'HeadsetSolid': '\uF348',
      'Health': '\uE95E',
      'HealthRefresh': '\uE3BD',
      'HealthSolid': '\uF33F',
      'Heart': '\uEB51',
      'HeartBroken': '\uEA92',
      'HeartFill': '\uEB52',
      'Help': '\uE897',
      'HelpMirrored': '\uEA51',
      'HexaditeInvestigation': '\uE3F8',
      'HexaditeInvestigationCancel': '\uE3F9',
      'HexaditeInvestigationSemiAuto': '\uE3FA',
      'Hexagon': '\uF4FE',
      'Hide': '\uED1A',
      'Hide2': '\uEF89',
      'Hide3': '\uF6AC',
      'HideVisualFilter': '\uF403',
      'Highlight': '\uE7E6',
      'HighlightMappedShapes': '\uF2A1',
      'HintText': '\uF50F',
      'HistoricalWeather': '\uEB43',
      'History': '\uE81C',
      'Home': '\uE80F',
      'HomeDropdown': '\uE427',
      'HomeGroup': '\uEC26',
      'HomeSolid': '\uEA8A',
      'HomeVerify': '\uF00E',
      'HorizontalDistributeCenter': '\uF4F9',
      'HorizontalTabKey': '\uE7FD',
      'Hospital': '\uE91D',
      'Hot': '\uECE2',
      'Hotel': '\uE824',
      'HourGlass': '\uEA03',
      'Ice': '\uE473',
      'IconSetsFlag': '\uF2A4',
      'IDBadge': '\uF427',
      'IgnoreConversation': '\uE372',
      'ImageCrosshair': '\uF2C9',
      'ImageDiff': '\uF30B',
      'ImageInAR': '\uE420',
      'ImagePixel': '\uF30C',
      'ImageSearch': '\uF4E8',
      'Import': '\uE8B5',
      'ImportAllMirrored': '\uEA53',
      'Important': '\uE8C9',
      'ImportMirrored': '\uEA52',
      'Inbox': '\uF41C',
      'InboxActive': '\uE497',
      'InboxCheck': '\uEF64',
      'IncidentTriangle': '\uE814',
      'IncomingCall': '\uE77E',
      'IncreaseIndent': '\uE399',
      'IncreaseIndentArrow': '\uF7A1',
      'IncreaseIndentArrowMirrored': '\uF7A5',
      'IncreaseIndentHanging': '\uE39D',
      'IncreaseIndentHangingMirrored': '\uE39E',
      'IncreaseIndentMirrored': '\uE39A',
      'IncreaseIndentText': '\uF7A0',
      'IncreaseIndentTextMirrored': '\uF7A4',
      'IndentFirstLine': '\uE3DD',
      'Info': '\uE946',
      'Info12': '\uE55A',
      'Info2': '\uEA1F',
      'InformationBarriers': '\uF803',
      'InfoSolid': '\uF167',
      'InkingTool': '\uE76D',
      'InputAddress': '\uE41E',
      'Insert': '\uF278',
      'InsertColumnsLeft': '\uF64A',
      'InsertColumnsRight': '\uF64B',
      'InsertRowsAbove': '\uF64C',
      'InsertRowsBelow': '\uF64D',
      'InsertSignatureLine': '\uF677',
      'InsertTextBox': '\uEC7D',
      'InsertTextBoxKorean': '\uE5D3',
      'Insights': '\uE3AF',
      'Installation': '\uE311',
      'InstallToDrive': '\uF28D',
      'IntermittentCloudsDay': '\uE46A',
      'IntermittentCloudsNight': '\uE478',
      'InternalInvestigation': '\uF854',
      'InternetSharing': '\uE704'
    }
  };

  registerIcons(subset, options);
}
