  // Your use of the content in the files referenced here is subject to the terms of the license at https://aka.ms/fabric-assets-license

// tslint:disable:max-line-length

import {
  IIconOptions,
  IIconSubset,
  registerIcons
} from '@uifabric/styling';

export function initializeIcons(
  baseUrl: string = '',
  options?: IIconOptions
): void {
  const subset: IIconSubset = {
    style: {
      MozOsxFontSmoothing: 'grayscale',
      WebkitFontSmoothing: 'antialiased',
      fontStyle: 'normal',
      fontWeight: 'normal',
      speak: 'none'
    },
    fontFace: {
      fontFamily: `"FabricMDL2Icons-0"`,
      src: `url('${baseUrl}fabric-icons-0-0f4c4510.woff') format('woff')`
    },
    icons: {
      '12PointStar': '\uF505',
      '6PointStar': '\uF504',
      'AADLogo': '\uED68',
      'Accept': '\uE8FB',
      'AcceptMedium': '\uF78C',
      'AccessibiltyChecker': '\uF835',
      'AccessLogo': '\uED69',
      'AccountActivity': '\uEFF4',
      'AccountBrowser': '\uF652',
      'AccountManagement': '\uF55C',
      'Accounts': '\uE910',
      'ActionCenter': '\uE91C',
      'ActivateOrders': '\uEFE0',
      'ActivityFeed': '\uF056',
      'Add': '\uE710',
      'AddBookmark': '\uF5B7',
      'AddConnection': '\uF4E1',
      'AddEvent': '\uEEB5',
      'AddFavorite': '\uF0C8',
      'AddFavoriteFill': '\uF0C9',
      'AddField': '\uE4C7',
      'AddFriend': '\uE8FA',
      'AddGroup': '\uEE3D',
      'AddHome': '\uF17B',
      'AddIn': '\uF775',
      'AddLink': '\uE35E',
      'AddMedium': '\uECA1',
      'AddMultiple': '\uE9C5',
      'AddNotes': '\uEAE3',
      'AddOnlineMeeting': '\uED8E',
      'AddPhone': '\uED96',
      'AddReaction': '\uF85D',
      'AddSpaceAfter': '\uE3DF',
      'AddSpaceBefore': '\uE3DE',
      'AddTable': '\uE4C6',
      'AddTo': '\uECC8',
      'AddToShoppingList': '\uEA9A',
      'AddWork': '\uF17C',
      'Admin': '\uE7EF',
      'AdminALogo32': '\uF4BA',
      'AdminALogoFill32': '\uF4BB',
      'AdminALogoInverse32': '\uED6A',
      'AdminCLogoInverse32': '\uED6B',
      'AdminDLogoInverse32': '\uED6C',
      'AdminELogoInverse32': '\uED6D',
      'AdminLLogoInverse32': '\uED6E',
      'AdminMLogoInverse32': '\uED6F',
      'AdminOLogoInverse32': '\uED70',
      'AdminPLogoInverse32': '\uED71',
      'AdminSLogoInverse32': '\uED72',
      'AdminYLogoInverse32': '\uED73',
      'Airplane': '\uE709',
      'AirplaneSolid': '\uEB4C',
      'AirTickets': '\uEF7A',
      'AlarmClock': '\uE919',
      'Album': '\uE7AB',
      'AlbumRemove': '\uEC62',
      'AlertSettings': '\uF8B6',
      'AlertSolid': '\uF331',
      'AlignCenter': '\uE8E3',
      'AlignHorizontalCenter': '\uF4F4',
      'AlignHorizontalLeft': '\uF4F3',
      'AlignHorizontalRight': '\uF4F5',
      'AlignJustify': '\uF51E',
      'AlignLeft': '\uE8E4',
      'AlignRight': '\uE8E2',
      'AlignVerticalBottom': '\uF4F8',
      'AlignVerticalCenter': '\uF4F7',
      'AlignVerticalTop': '\uF4F6',
      'AllApps': '\uE71D',
      'AllAppsMirrored': '\uEA40',
      'AllCurrency': '\uEAE4',
      'AltText': '\uE397',
      'AnalyticsLogo': '\uF1DE',
      'AnalyticsQuery': '\uF1DF',
      'AnalyticsReport': '\uF1E1',
      'AnalyticsView': '\uF5F1',
      'AnchorLock': '\uF511',
      'Annotation': '\uE924',
      'AppIconDefault': '\uECAA',
      'AppIconDefaultAdd': '\uEFDA',
      'AppIconDefaultEdit': '\uEFDC',
      'AppIconDefaultList': '\uEFDE',
      'AppIconSecure': '\uE657',
      'AppsContent': '\uEE54',
      'Archive': '\uF03F',
      'ArchiveUndo': '\uE3A1',
      'AreaChart': '\uE9D2',
      'ArrangeBringForward': '\uF509',
      'ArrangeBringToFront': '\uF506',
      'ArrangeByFrom': '\uF678',
      'ArrangeSendBackward': '\uF508',
      'ArrangeSendToBack': '\uF507',
      'Arrivals': '\uEB34',
      'ArrowDownRight8': '\uEED5',
      'ArrowDownRightMirrored8': '\uEEF0',
      'ArrowTallDownLeft': '\uF2BF',
      'ArrowTallDownRight': '\uF2C0',
      'ArrowTallUpLeft': '\uF2BD',
      'ArrowTallUpRight': '\uF2BE'
    }
  };

  registerIcons(subset, options);
}
