  // Your use of the content in the files referenced here is subject to the terms of the license at https://aka.ms/fabric-assets-license

// tslint:disable:max-line-length

import {
  IIconOptions,
  IIconSubset,
  registerIcons
} from '@uifabric/styling';

export function initializeIcons(
  baseUrl: string = '',
  options?: IIconOptions
): void {
  const subset: IIconSubset = {
    style: {
      MozOsxFontSmoothing: 'grayscale',
      WebkitFontSmoothing: 'antialiased',
      fontStyle: 'normal',
      fontWeight: 'normal',
      speak: 'none'
    },
    fontFace: {
      fontFamily: `"FabricMDL2Icons-17"`,
      src: `url('${baseUrl}fabric-icons-17-5eba15a6.woff') format('woff')`
    },
    icons: {
      'ReservationOrders': '\uF845',
      'Reset': '\uE423',
      'ResetDevice': '\uED10',
      'ResponsesMenu': '\uF768',
      'ReturnKey': '\uE751',
      'ReturnToSession': '\uED24',
      'RevenueManagement': '\uF85E',
      'ReviewRequestMirroredSolid': '\uF357',
      'ReviewRequestSolid': '\uF356',
      'ReviewResponseSolid': '\uF358',
      'ReviewSolid': '\uF355',
      'RevToggleKey': '\uE845',
      'RewardsLogo': '\uED4E',
      'RewardsLogoArt64': '\uEEF2',
      'RewardsLogoSolid': '\uED4F',
      'Rewind': '\uEB9E',
      'RewindEightX': '\uE449',
      'RewindFourX': '\uE448',
      'RewindOneFiveX': '\uE446',
      'RewindOneX': '\uE445',
      'RewindPointFiveX': '\uE444',
      'RewindTwoX': '\uE447',
      'Ribbon': '\uE9D1',
      'Ribbon2': '\uF19B',
      'RibbonSolid': '\uF345',
      'RightDoubleQuote': '\uE9B1',
      'RightKey': '\uF265',
      'RightTriangle': '\uF500',
      'Ringer': '\uEA8F',
      'RingerActive': '\uE498',
      'RingerOff': '\uF2C5',
      'RingerRemove': '\uF279',
      'RingerSolid': '\uEF3A',
      'Robot': '\uE99A',
      'Rocket': '\uF3B3',
      'Room': '\uED9F',
      'Rotate': '\uE7AD',
      'Rotate90Clockwise': '\uF80D',
      'Rotate90CounterClockwise': '\uF80E',
      'RowsChild': '\uF29C',
      'RowsGroup': '\uF29B',
      'RSSFeed': '\uF80C',
      'Rugby': '\uEB2D',
      'Running': '\uEADA',
      'Sad': '\uE757',
      'SadSolid': '\uF33E',
      'SamsungGallery': '\uE4E2',
      'Save': '\uE74E',
      'SaveAll': '\uF203',
      'SaveAndClose': '\uF038',
      'SaveAndPublish': '\uF671',
      'SaveAs': '\uE792',
      'SavedOffline': '\uE546',
      'SaveTemplate': '\uF6EC',
      'SaveToMobile': '\uF7E0',
      'Savings': '\uEB0B',
      'ScaleUp': '\uED09',
      'ScaleVolume': '\uF18C',
      'ScatterChart': '\uEFEB',
      'ScheduleEventAction': '\uF1EF',
      'SchoolDataSyncLogo': '\uE34C',
      'ScopeTemplate': '\uF2B0',
      'Screen': '\uEF39',
      'ScreenCast': '\uF7E2',
      'ScreenPreviewOn': '\uF11E',
      'ScreenTime': '\uF182',
      'Script': '\uF03A',
      'ScrollUpDown': '\uEC8F',
      'SDCard': '\uE7F1',
      'Search': '\uE721',
      'SearchAndApps': '\uE773',
      'SearchArt64': '\uEEF5',
      'SearchBookmark': '\uF5B8',
      'SearchCalendar': '\uF4AF',
      'SearchData': '\uF3F1',
      'SearchIssue': '\uF09A',
      'SearchIssueMirrored': '\uF09B',
      'SearchNearby': '\uE820',
      'SecondaryNav': '\uF814',
      'Section': '\uEC0C',
      'Sections': '\uEF76',
      'SecurityCamera': '\uEB35',
      'SecurityGroup': '\uED85',
      'SecurityTest': '\uE48F',
      'SeeDo': '\uE808',
      'SelectAll': '\uE8B3',
      'Sell': '\uEB0C',
      'SemiboldWeight': '\uF4F0',
      'Send': '\uE724',
      'SendMirrored': '\uEA63',
      'SentimentAnalysis': '\uE393',
      'Separator': '\uF35E',
      'Server': '\uF201',
      'ServerEnviroment': '\uF29F',
      'ServerProcesses': '\uF1FE',
      'ServiceActivity': '\uEFF1',
      'ServiceOff': '\uE3FD',
      'SetAction': '\uF071',
      'Settings': '\uE713',
      'SettingsAdd': '\uE35A'
    }
  };

  registerIcons(subset, options);
}
