  // Your use of the content in the files referenced here is subject to the terms of the license at https://aka.ms/fabric-assets-license

// tslint:disable:max-line-length

import {
  IIconOptions,
  IIconSubset,
  registerIcons
} from '@uifabric/styling';

export function initializeIcons(
  baseUrl: string = '',
  options?: IIconOptions
): void {
  const subset: IIconSubset = {
    style: {
      MozOsxFontSmoothing: 'grayscale',
      WebkitFontSmoothing: 'antialiased',
      fontStyle: 'normal',
      fontWeight: 'normal',
      speak: 'none'
    },
    fontFace: {
      fontFamily: `"FabricMDL2Icons-1"`,
      src: `url('${baseUrl}fabric-icons-1-667b2ff0.woff') format('woff')`
    },
    icons: {
      'ArrowUpRight': '\uF069',
      'ArrowUpRight8': '\uEED4',
      'ArrowUpRightMirrored8': '\uEEEF',
      'Articles': '\uEAC1',
      'Ascending': '\uEDC0',
      'AspectRatio': '\uE799',
      'AssessmentGroup': '\uF31A',
      'AssessmentGroupTemplate': '\uF2B1',
      'AssetLibrary': '\uEEB6',
      'Assign': '\uE9D3',
      'AssignPolicy': '\uE461',
      'Asterisk': '\uEA38',
      'AsteriskSolid': '\uF34D',
      'ATPLogo': '\uEF85',
      'Attach': '\uE723',
      'AustralianRules': '\uEE70',
      'AuthenticatorApp': '\uF6B1',
      'AutoDeploySettings': '\uF3FA',
      'AutoEnhanceOff': '\uE78E',
      'AutoEnhanceOn': '\uE78D',
      'AutoFillTemplate': '\uF313',
      'AutoFitContents': '\uE3E8',
      'AutoFitWindow': '\uE3E9',
      'AutoHeight': '\uF512',
      'AutomateFlow': '\uE3F5',
      'AutoRacing': '\uEB24',
      'AwayStatus': '\uEE6A',
      'AzureAPIManagement': '\uF37F',
      'AzureDataExplorer': '\uE439',
      'AzureIcon': '\uEB6A',
      'AzureKeyVault': '\uF3B4',
      'AzureServiceEndpoint': '\uF380',
      'Back': '\uE72B',
      'BackgroundColor': '\uF42B',
      'Backlog': '\uF2AC',
      'BacklogBoard': '\uF444',
      'BacklogList': '\uF6BF',
      'BackToWindow': '\uE73F',
      'Badge': '\uEC1B',
      'Balloons': '\uED7E',
      'Bank': '\uE825',
      'BankSolid': '\uF34F',
      'BarChart3': '\uEAE6',
      'BarChart3One': '\uE68C',
      'BarChart3Two': '\uE68D',
      'BarChart3Zero': '\uE68B',
      'BarChart4': '\uEAE7',
      'BarChartHorizontal': '\uE9EB',
      'BarChartVertical': '\uE9EC',
      'BarChartVerticalEdit': '\uF89D',
      'BarChartVerticalFill': '\uF830',
      'BarChartVerticalFilter': '\uF77E',
      'BarChartVerticalFilterSolid': '\uF77F',
      'Baseball': '\uEB20',
      'BeerMug': '\uF49E',
      'BIDashboard': '\uF543',
      'BidiLtr': '\uE9AA',
      'Bidirectional': '\uE688',
      'BidiRtl': '\uE9AB',
      'Bill': '\uE5FA',
      'BingLogo': '\uEB6B',
      'BirthdayCake': '\uEF8D',
      'BlobStorage': '\uE436',
      'BlockContact': '\uE8F8',
      'Blocked': '\uE733',
      'Blocked12': '\uF62E',
      'Blocked2': '\uECE4',
      'Blocked2Solid': '\uF737',
      'BlockedSite': '\uE72F',
      'BlockedSiteSolid12': '\uF70A',
      'BlockedSolid': '\uF531',
      'Blog': '\uF22B',
      'BlowingSnow': '\uE9C9',
      'Blur': '\uF28E',
      'Boards': '\uEF68',
      'Bold': '\uE8DD',
      'BoldBulgarian': '\uE5C5',
      'BoldF': '\uE5B5',
      'BoldG': '\uE5B3',
      'BoldK': '\uE5C6',
      'BoldKazakh': '\uE5C9',
      'BoldKorean': '\uE5BD',
      'BoldN': '\uE5B7',
      'BoldP': '\uE5C7',
      'BoldRussion': '\uE5B9',
      'BoldSerbian': '\uE5CA',
      'BoldT': '\uE5C8',
      'BookAnswers': '\uF8A4',
      'BookingsLogo': '\uEDC7',
      'BookmarkReport': '\uF76B',
      'Bookmarks': '\uE8A4',
      'BookmarksMirrored': '\uEA41',
      'BooleanData': '\uE678',
      'BorderAll': '\uE5F4',
      'BorderDash': '\uF50A',
      'BorderDot': '\uF50B',
      'BorderInside': '\uE5F3',
      'BorderInsideHorizontal': '\uE5F2',
      'BorderInsideVertical': '\uE5F1',
      'BorderNone': '\uE5F0'
    }
  };

  registerIcons(subset, options);
}
