  // Your use of the content in the files referenced here is subject to the terms of the license at https://aka.ms/fabric-assets-license

// tslint:disable:max-line-length

import {
  IIconOptions,
  IIconSubset,
  registerIcons
} from '@uifabric/styling';

export function initializeIcons(
  baseUrl: string = '',
  options?: IIconOptions
): void {
  const subset: IIconSubset = {
    style: {
      MozOsxFontSmoothing: 'grayscale',
      WebkitFontSmoothing: 'antialiased',
      fontStyle: 'normal',
      fontWeight: 'normal',
      speak: 'none'
    },
    fontFace: {
      fontFamily: `"FabricMDL2Icons-12"`,
      src: `url('${baseUrl}fabric-icons-12-88257a2f.woff') format('woff')`
    },
    icons: {
      'MailReplyMirrored': '\uEA57',
      'MailSchedule': '\uF72E',
      'MailSecure': '\uE4D4',
      'MailSolid': '\uF343',
      'MailTentative': '\uF416',
      'MailTentativeMirrored': '\uF417',
      'MailUndelivered': '\uF415',
      'ManagerSelfService': '\uEE23',
      'Manufacturing': '\uE99C',
      'MapDirections': '\uE816',
      'MapLayers': '\uE81E',
      'MapPin': '\uE707',
      'MapPin12': '\uE3AE',
      'MapPinSolid': '\uF52E',
      'MarkAsProtected': '\uF6AE',
      'MarkDownLanguage': '\uF2FB',
      'Market': '\uEAFC',
      'MarketDown': '\uEF42',
      'MasterDatabase': '\uF5BA',
      'MaximumValue': '\uF5BC',
      'Medal': '\uEE38',
      'MedalSolid': '\uF6B9',
      'Media': '\uEA69',
      'MediaAdd': '\uF510',
      'Medical': '\uEAD4',
      'MedicalCare': '\uE54D',
      'MedicationAdmin': '\uE54E',
      'MedicationRequest': '\uE54F',
      'Megaphone': '\uE789',
      'MegaphoneSolid': '\uF332',
      'Memo': '\uE77C',
      'Merge': '\uE7D5',
      'MergeCase': '\uEFC9',
      'MergeDuplicate': '\uF29A',
      'Message': '\uE8BD',
      'MessageFill': '\uEC70',
      'MessageFriendRequest': '\uF055',
      'MetricsFailure': '\uE4CE',
      'MetricsInstall': '\uE4CD',
      'MetricsUsage': '\uE4CC',
      'MicOff': '\uEC54',
      'MicOff2': '\uF781',
      'Microphone': '\uE720',
      'MicrosoftStaffhubLogo': '\uF130',
      'MicrosoftTranslatorLogo': '\uF782',
      'MicrosoftTranslatorLogoBlue': '\uF853',
      'MicrosoftTranslatorLogoGreen': '\uF852',
      'MiniContract': '\uE93B',
      'MiniContractMirrored': '\uEA59',
      'MiniExpand': '\uE93A',
      'MiniExpandMirrored': '\uEA5A',
      'MiniLink': '\uE732',
      'MinimumValue': '\uF5BD',
      'MobileAngled': '\uE463',
      'MobileReport': '\uF18A',
      'MobileSelected': '\uEC75',
      'ModelAppTemplate32': '\uE5FD',
      'ModelingView': '\uF871',
      'Money': '\uEAFD',
      'More': '\uE712',
      'MoreSports': '\uEB22',
      'MoreVertical': '\uF2BC',
      'MostyClearNight': '\uE476',
      'MostyCloudyFlurriesDay': '\uE471',
      'MostyCloudyFlurriesNight': '\uE47D',
      'MostyCloudyShowersDay': '\uE46D',
      'MostyCloudyTStormsDay': '\uE46F',
      'MostyCloudyTStormsNight': '\uE47B',
      'MostySunnyDay': '\uE468',
      'MountainClimbing': '\uF6DB',
      'Move': '\uE7C2',
      'Movers': '\uEBCD',
      'MoveToFolder': '\uE8DE',
      'MSListsConnected': '\uE601',
      'MSNLogo': '\uEB6C',
      'MSNVideos': '\uEB1C',
      'MSNVideosSolid': '\uF2DA',
      'MSNVolume': '\uEB15',
      'MultiSelect': '\uE762',
      'MultiSelectMirrored': '\uEA98',
      'MusicInCollection': '\uE940',
      'MusicInCollectionFill': '\uEA36',
      'MusicNote': '\uEC4F',
      'MuteChat': '\uF17A',
      'MyMoviesTV': '\uEE6C',
      'MyNetwork': '\uEC27',
      'Nav2DMapView': '\uE800',
      'NavigateBack': '\uF2DD',
      'NavigateBackMirrored': '\uF2DE',
      'NavigateExternalInline': '\uF35F',
      'NavigateForward': '\uF2DF',
      'NavigateForwardMirrored': '\uF2E0',
      'NavigationFlipper': '\uF51D',
      'NetworkDeviceScanning': '\uE4F6',
      'NetworkTower': '\uEC05',
      'NewAnalyticsQuery': '\uF1E0',
      'NewFolder': '\uE8F4',
      'NewMail': '\uF7EA',
      'News': '\uE900',
      'NewsSearch': '\uF4E9'
    }
  };

  registerIcons(subset, options);
}
