  // Your use of the content in the files referenced here is subject to the terms of the license at https://aka.ms/fabric-assets-license

// tslint:disable:max-line-length

import {
  IIconOptions,
  IIconSubset,
  registerIcons
} from '@uifabric/styling';

export function initializeIcons(
  baseUrl: string = '',
  options?: IIconOptions
): void {
  const subset: IIconSubset = {
    style: {
      MozOsxFontSmoothing: 'grayscale',
      WebkitFontSmoothing: 'antialiased',
      fontStyle: 'normal',
      fontWeight: 'normal',
      speak: 'none'
    },
    fontFace: {
      fontFamily: `"FabricMDL2Icons-13"`,
      src: `url('${baseUrl}fabric-icons-13-739e2787.woff') format('woff')`
    },
    icons: {
      'NewTeamProject': '\uF2B2',
      'Next': '\uE893',
      'NormalWeight': '\uF4EF',
      'NoteForward': '\uED99',
      'NotePinned': '\uED9A',
      'NoteReply': '\uED98',
      'NotExecuted': '\uF440',
      'NotImpactedSolid': '\uF441',
      'NugetLogo': '\uF44C',
      'NUIFace': '\uEB68',
      'Number': '\uF691',
      'NumberedList': '\uEA1C',
      'NumberedListMirrored': '\uE398',
      'NumberedListNumber': '\uF797',
      'NumberedListNumberMirrored': '\uF799',
      'NumberedListText': '\uF796',
      'NumberedListTextMirrored': '\uF798',
      'NumberField': '\uEDC4',
      'NumberSequence': '\uF52A',
      'NumberSymbol': '\uF7AC',
      'Oauth': '\uE5C3',
      'ObjectRecognition': '\uE4EE',
      'Octagon': '\uF4FD',
      'ODLink': '\uE4BB',
      'ODLink12': '\uE4BC',
      'ODSharedChannel': '\uE649',
      'ODSharedChannel12': '\uE64A',
      'OEM': '\uE74C',
      'OfficeAddinsLogo': '\uEEC7',
      'OfficeAssistantLogo': '\uEDCE',
      'OfficeCatchUp': '\uE490',
      'OfficeChat': '\uF70F',
      'OfficeChatSolid': '\uF710',
      'OfficeFormsLogo': '\uF434',
      'OfficeFormsLogo16': '\uF436',
      'OfficeFormsLogo24': '\uF43B',
      'OfficeFormsLogoInverse': '\uEF86',
      'OfficeFormsLogoInverse16': '\uF433',
      'OfficeFormsLogoInverse24': '\uF43A',
      'OfficeLogo': '\uEB6E',
      'OfficeStoreLogo': '\uEDCF',
      'OfficeVideoLogo': '\uF282',
      'OfficeVideoLogoFill': '\uF283',
      'OfficeVideoLogoInverse': '\uED7A',
      'OfflineOneDriveParachute': '\uEEC8',
      'OfflineOneDriveParachuteDisabled': '\uEEC9',
      'OfflineStorage': '\uEC8C',
      'OfflineStorageSolid': '\uF34E',
      'Onboarding': '\uF3BA',
      'OneDriveAdd': '\uEF32',
      'OneDriveFolder16': '\uF53B',
      'OneDriveLogo': '\uE941',
      'OneNoteDocType': '\uF04F',
      'OneNoteEduLogoInverse': '\uEDD0',
      'OneNoteLogo': '\uF1E7',
      'OneNoteLogo16': '\uF39A',
      'OneNoteLogoInverse': '\uEC0D',
      'OneNoteLogoInverse16': '\uF399',
      'OpenEnrollment': '\uEF1C',
      'OpenFile': '\uE8E5',
      'OpenFolderHorizontal': '\uED25',
      'OpenInNewTab': '\uF6AB',
      'OpenInNewWindow': '\uE8A7',
      'OpenPane': '\uE8A0',
      'OpenPaneMirrored': '\uEA5B',
      'OpenSource': '\uEBC2',
      'OpenWith': '\uE7AC',
      'OpenWithMirrored': '\uEA5C',
      'Opportunities': '\uF05F',
      'OrderLock': '\uE4CB',
      'Org': '\uECA6',
      'Orientation': '\uE8B4',
      'Orientation2': '\uF7E1',
      'OutlookLogo': '\uF1E9',
      'OutlookLogo16': '\uF39D',
      'OutlookLogoInverse': '\uEB6D',
      'OutlookLogoInverse16': '\uF39C',
      'OutlookSpacesBucket': '\uE481',
      'OutOfOffice': '\uED34',
      'PAAction': '\uE60B',
      'Package': '\uE7B8',
      'Packages': '\uF318',
      'Padding': '\uF518',
      'PaddingBottom': '\uF51A',
      'PaddingLeft': '\uF51B',
      'PaddingRight': '\uF51C',
      'PaddingTop': '\uF519',
      'Page': '\uE7C3',
      'PageAdd': '\uEA1A',
      'PageArrowRight': '\uEFB8',
      'PageBlock': '\uEFB5',
      'PageCheckedin': '\uF104',
      'PageCheckedOut': '\uF02C',
      'PageData': '\uE31C',
      'PageEdit': '\uEFB6',
      'PageHeader': '\uECEE',
      'PageHeaderEdit': '\uE31D',
      'PageLeft': '\uE760',
      'PageLink': '\uE302',
      'PageList': '\uF106'
    }
  };

  registerIcons(subset, options);
}
