  // Your use of the content in the files referenced here is subject to the terms of the license at https://aka.ms/fabric-assets-license

// tslint:disable:max-line-length

import {
  IIconOptions,
  IIconSubset,
  registerIcons
} from '@uifabric/styling';

export function initializeIcons(
  baseUrl: string = '',
  options?: IIconOptions
): void {
  const subset: IIconSubset = {
    style: {
      MozOsxFontSmoothing: 'grayscale',
      WebkitFontSmoothing: 'antialiased',
      fontStyle: 'normal',
      fontWeight: 'normal',
      speak: 'none'
    },
    fontFace: {
      fontFamily: `"FabricMDL2Icons-11"`,
      src: `url('${baseUrl}fabric-icons-11-ac3701f9.woff') format('woff')`
    },
    icons: {
      'IntersectShape': '\uF8FD',
      'Invoice': '\uE9DC',
      'IOT': '\uF22C',
      'IoTSecure': '\uE4D6',
      'IRMForward': '\uF41F',
      'IRMForwardMirrored': '\uF420',
      'IRMReply': '\uF41D',
      'IRMReplyMirrored': '\uF41E',
      'IssueSolid': '\uF448',
      'IssueTracking': '\uEEC0',
      'IssueTrackingMirrored': '\uEEC1',
      'Italic': '\uE8DB',
      'ItalicC': '\uE5B2',
      'ItalicD': '\uE5CE',
      'ItalicK': '\uE5B6',
      'ItalicKazakh': '\uE5D2',
      'ItalicKorean': '\uE5BC',
      'ItalicL': '\uE5D1',
      'ItalicS': '\uE5CF',
      'ItalicT': '\uE5D0',
      'JavaScriptLanguage': '\uF2EE',
      'JoinOnlineMeeting': '\uED8F',
      'JS': '\uEBF0',
      'KaizalaLogo': '\uF492',
      'KeyboardClassic': '\uE765',
      'KeyPhraseExtraction': '\uE395',
      'KnowledgeArticle': '\uF000',
      'KnowledgeManagementApp': '\uE4FC',
      'Label': '\uE932',
      'LadybugSolid': '\uF44A',
      'Lamp': '\uEB19',
      'LandscapeOrientation': '\uEF6B',
      'LaptopSecure': '\uF552',
      'LaptopSelected': '\uEC76',
      'LargeGrid': '\uEECB',
      'LearningApp': '\uE5D8',
      'LearningTools': '\uF7DB',
      'Leave': '\uF627',
      'LeaveUser': '\uE3A8',
      'LeftKey': '\uF264',
      'Library': '\uE8F1',
      'LibraryAddTo': '\uE60D',
      'Lifesaver': '\uEF62',
      'LifesaverLock': '\uEF63',
      'Light': '\uE793',
      'Lightbulb': '\uEA80',
      'LightbulbSolid': '\uE681',
      'LightningBolt': '\uE945',
      'LightningBoltSolid': '\uE45F',
      'LightningSecure': '\uE4D3',
      'LightSnow': '\uEA02',
      'LightWeight': '\uF4EE',
      'Like': '\uE8E1',
      'LikeSolid': '\uF3BF',
      'Line': '\uF4FC',
      'LineChart': '\uE9E6',
      'LineSpacing': '\uF517',
      'LineStyle': '\uF50C',
      'LineThickness': '\uF50D',
      'Link': '\uE71B',
      'Link12': '\uF6E3',
      'LinkedDatabase': '\uF779',
      'LinkedInLogo': '\uF20A',
      'List': '\uEA37',
      'ListMirrored': '\uEA55',
      'LiveSite': '\uF6A6',
      'LocalAdmin': '\uF1FB',
      'LocaleLanguage': '\uF2B7',
      'Location': '\uE81D',
      'LocationCircle': '\uE80E',
      'LocationDot': '\uE827',
      'LocationFill': '\uE920',
      'LocationOutline': '\uF2D0',
      'Lock': '\uE72E',
      'Lock12': '\uF6E6',
      'LockShare': '\uE455',
      'LockSolid': '\uE9A2',
      'LogRemove': '\uF316',
      'LookupEntities': '\uF5B5',
      'LowerBrightness': '\uEC8A',
      'LowerCase': '\uE5EE',
      'LyncLogo': '\uED79',
      'M365InvoicingLogo': '\uF7C1',
      'MachineLearning': '\uE3B8',
      'Mail': '\uE715',
      'MailAlert': '\uED80',
      'MailAttached': '\uF774',
      'MailCheck': '\uED81',
      'MailFill': '\uE8A8',
      'MailForward': '\uE89C',
      'MailForwardMirrored': '\uEA56',
      'MailLink': '\uEFAC',
      'MailLowImportance': '\uED82',
      'MailOptions': '\uF82C',
      'MailPause': '\uED83',
      'MailReminder': '\uF418',
      'MailRepeat': '\uED84',
      'MailReply': '\uE8CA',
      'MailReplyAll': '\uE8C2',
      'MailReplyAllMirrored': '\uEA58'
    }
  };

  registerIcons(subset, options);
}
