  // Your use of the content in the files referenced here is subject to the terms of the license at https://aka.ms/fabric-assets-license

// tslint:disable:max-line-length

import {
  IIconOptions,
  IIconSubset,
  registerIcons
} from '@uifabric/styling';

export function initializeIcons(
  baseUrl: string = '',
  options?: IIconOptions
): void {
  const subset: IIconSubset = {
    style: {
      MozOsxFontSmoothing: 'grayscale',
      WebkitFontSmoothing: 'antialiased',
      fontStyle: 'normal',
      fontWeight: 'normal',
      speak: 'none'
    },
    fontFace: {
      fontFamily: `"FabricMDL2Icons-19"`,
      src: `url('${baseUrl}fabric-icons-19-8536d0fb.woff') format('woff')`
    },
    icons: {
      'StackedBarChartFullSettings': '\uF1E6',
      'StackedColumnChart2': '\uF666',
      'StackedColumnChart2Fill': '\uF831',
      'StackedLineChart': '\uF24E',
      'StackIndicator': '\uE7FF',
      'StaffNotebookLogo16': '\uF48E',
      'StaffNotebookLogo32': '\uF48C',
      'StaffNotebookLogoFill16': '\uF48F',
      'StaffNotebookLogoFill32': '\uF48D',
      'StaffNotebookLogoInverted16': '\uF491',
      'StaffNotebookLogoInverted32': '\uF490',
      'Starburst': '\uEF78',
      'StarburstSolid': '\uF33C',
      'StatusCircleBlock': '\uF140',
      'StatusCircleBlock2': '\uF141',
      'StatusCircleCheckmark': '\uF13E',
      'StatusCircleErrorX': '\uF13D',
      'StatusCircleExclamation': '\uF13C',
      'StatusCircleInfo': '\uF13F',
      'StatusCircleInner': '\uF137',
      'StatusCircleOuter': '\uF136',
      'StatusCircleQuestionMark': '\uF142',
      'StatusCircleRing': '\uF138',
      'StatusCircleSync': '\uF143',
      'StatusErrorFull': '\uEB90',
      'StatusTriangle': '\uEA82',
      'StatusTriangleExclamation': '\uF13B',
      'StatusTriangleInner': '\uF13A',
      'StatusTriangleOuter': '\uF139',
      'Step': '\uF241',
      'StepBackward': '\uE68E',
      'StepInsert': '\uF242',
      'StepInto': '\uE690',
      'StepOut': '\uE691',
      'StepOver': '\uE68F',
      'StepShared': '\uF243',
      'StepSharedAdd': '\uF244',
      'StepSharedInsert': '\uF245',
      'StickyNotesOutlineAppIcon': '\uE36A',
      'StickyNotesSolidAppIcon': '\uE36B',
      'StockDown': '\uEB0F',
      'StockUp': '\uEB11',
      'Stop': '\uE71A',
      'StopSolid': '\uEE95',
      'Stopwatch': '\uE916',
      'StorageAcount': '\uE435',
      'StorageOptical': '\uE958',
      'StoreLogo16': '\uEA96',
      'StoreLogoMed20': '\uEA04',
      'Storyboard': '\uF308',
      'StreamDiscover': '\uF7D9',
      'Streaming': '\uE93E',
      'StreamingDataflow': '\uE668',
      'StreamingDataset': '\uE667',
      'StreamingOff': '\uF2BB',
      'StreamLogo': '\uF329',
      'StreamPlaylist': '\uE669',
      'Street': '\uE913',
      'StreetsideSplitMinimize': '\uE802',
      'Strikethrough': '\uEDE0',
      'StrikethroughKorean': '\uE5D4',
      'Subscribe': '\uEDA1',
      'Subscript': '\uEDDF',
      'SubstitutionsIn': '\uEB31',
      'SubtractShape': '\uF8FC',
      'Suitcase': '\uEDD3',
      'SummaryChart': '\uE9FE',
      'SunAdd': '\uEF69',
      'Sunny': '\uE9BD',
      'SunQuestionMark': '\uEF6A',
      'Superscript': '\uEDDE',
      'SurveyQuestionResponse': '\uE4F2',
      'SurveyQuestions': '\uF01B',
      'SwayLogo16': '\uF484',
      'SwayLogo32': '\uF482',
      'SwayLogoFill16': '\uF485',
      'SwayLogoFill32': '\uF483',
      'SwayLogoInverse': '\uED29',
      'Switch': '\uE8AB',
      'SwitcherStartEnd': '\uE810',
      'SwitchUser': '\uE748',
      'Sync': '\uE895',
      'SyncError': '\uEA6A',
      'SyncFolder': '\uE8F7',
      'SyncOccurence': '\uF4A3',
      'SyncOccurenceCancel': '\uF7E7',
      'SyncStatus': '\uF751',
      'SyncStatusSolid': '\uF752',
      'SyncToPC': '\uEE6E',
      'System': '\uE770',
      'Tab': '\uE7E9',
      'TabCenter': '\uF100',
      'Table': '\uED86',
      'TableBrandedColumn': '\uE3F1',
      'TableBrandedRow': '\uE3EE',
      'TableColumn': '\uE4BD',
      'TableComputed': '\uF8F5',
      'TableFirstColumn': '\uE3EF',
      'TableGroup': '\uF6D9',
      'TableHeaderRow': '\uE3EC'
    }
  };

  registerIcons(subset, options);
}
