  // Your use of the content in the files referenced here is subject to the terms of the license at https://aka.ms/fabric-assets-license

// tslint:disable:max-line-length

import {
  IIconOptions,
  IIconSubset,
  registerIcons
} from '@uifabric/styling';

export function initializeIcons(
  baseUrl: string = '',
  options?: IIconOptions
): void {
  const subset: IIconSubset = {
    style: {
      MozOsxFontSmoothing: 'grayscale',
      WebkitFontSmoothing: 'antialiased',
      fontStyle: 'normal',
      fontWeight: 'normal',
      speak: 'none'
    },
    fontFace: {
      fontFamily: `"FabricMDL2Icons-7"`,
      src: `url('${baseUrl}fabric-icons-7-b2d3f1f2.woff') format('woff')`
    },
    icons: {
      'DoubleChevronLeftMed': '\uE991',
      'DoubleChevronLeftMedMirrored': '\uEA4D',
      'DoubleChevronRight': '\uEDBF',
      'DoubleChevronRight12': '\uEE99',
      'DoubleChevronRight8': '\uF36E',
      'DoubleChevronUp': '\uEDBD',
      'DoubleChevronUp12': '\uEE96',
      'DoubleChevronUp8': '\uF36C',
      'DoubleColumn': '\uF1D4',
      'DoubleColumnEdit': '\uF322',
      'DoubleDownArrow': '\uF769',
      'Down': '\uE74B',
      'DownKey': '\uF3E1',
      'Download': '\uE896',
      'DownloadDocument': '\uF549',
      'DragObject': '\uF553',
      'DrillDown': '\uF532',
      'DrillDownSolid': '\uF533',
      'DrillExpand': '\uF534',
      'DrillShow': '\uF535',
      'DrillThrough': '\uF5B9',
      'DriverOff': '\uE3FB',
      'DRM': '\uECA8',
      'Drop': '\uEB42',
      'Dropdown': '\uEDC5',
      'DropShape': '\uF1A8',
      'DropShapeSolid': '\uF63F',
      'DuplicateRow': '\uF82A',
      'Duststorm': '\uE9CD',
      'DynamicList': '\uE491',
      'Dynamics365Logo': '\uEDCC',
      'DynamicSMBLogo': '\uEDCD',
      'EaseOfAccess': '\uE776',
      'EatDrink': '\uE807',
      'EdgeLogo': '\uE3AB',
      'EdgeLogo16': '\uE3AA',
      'EdgeOldLogo': '\uEC60',
      'eDiscovery': '\uE370',
      'Edit': '\uE70F',
      'EditContact': '\uEFD3',
      'EditCreate': '\uF3C9',
      'EditEvent': '\uF05B',
      'EditListPencil': '\uE61B',
      'EditMail': '\uEF61',
      'EditMirrored': '\uEB7E',
      'EditNote': '\uED9D',
      'EditPhoto': '\uEF77',
      'EditSolid12': '\uF4B5',
      'EditSolidMirrored12': '\uF4B6',
      'EditStyle': '\uEF60',
      'EditTable': '\uE4C4',
      'Education': '\uE7BE',
      'Ellipse': '\uF4FB',
      'Embed': '\uECCE',
      'EMI': '\uE731',
      'Emoji': '\uE899',
      'Emoji2': '\uE76E',
      'EmojiDisappointed': '\uEA88',
      'EmojiNeutral': '\uEA87',
      'EmojiTabSymbols': '\uED58',
      'EmployeeSelfService': '\uEE24',
      'EmptyRecycleBin': '\uEF88',
      'Encounter': '\uE54C',
      'Encryption': '\uF69D',
      'EndPointSolid': '\uEB4B',
      'EngineeringGroup': '\uF362',
      'EntitlementPolicy': '\uE346',
      'EntitlementRedemption': '\uE347',
      'EntityExtraction': '\uE467',
      'EntryDecline': '\uF555',
      'EntryView': '\uF554',
      'Equalizer': '\uE9E9',
      'EraseTool': '\uE75C',
      'Error': '\uE783',
      'ErrorBadge': '\uEA39',
      'ErrorBadge12': '\uE558',
      'Event': '\uECA3',
      'Event12': '\uF763',
      'EventAccepted': '\uF422',
      'EventDate': '\uF059',
      'EventDateMissed12': '\uF764',
      'EventDeclined': '\uF425',
      'EventInfo': '\uED8B',
      'EventTentative': '\uF423',
      'EventTentativeMirrored': '\uF424',
      'EventToDoLogo': '\uF869',
      'ExcelDocument': '\uEF73',
      'ExcelLogo': '\uF1E5',
      'ExcelLogo16': '\uF397',
      'ExcelLogoInverse': '\uEC28',
      'ExcelLogoInverse16': '\uF396',
      'ExchangeLogo': '\uF284',
      'ExchangeLogoInverse': '\uED78',
      'ExerciseTracker': '\uEACC',
      'ExpandAll': '\uF859',
      'ExpandMenu': '\uEF67',
      'ExploreContent': '\uECCD',
      'ExploreContentSingle': '\uF164',
      'ExploreData': '\uF5B6',
      'Export': '\uEDE1'
    }
  };

  registerIcons(subset, options);
}
