  // Your use of the content in the files referenced here is subject to the terms of the license at https://aka.ms/fabric-assets-license

// tslint:disable:max-line-length

import {
  IIconOptions,
  IIconSubset,
  registerIcons
} from '@uifabric/styling';

export function initializeIcons(
  baseUrl: string = '',
  options?: IIconOptions
): void {
  const subset: IIconSubset = {
    style: {
      MozOsxFontSmoothing: 'grayscale',
      WebkitFontSmoothing: 'antialiased',
      fontStyle: 'normal',
      fontWeight: 'normal',
      speak: 'none'
    },
    fontFace: {
      fontFamily: `"FabricMDL2Icons-14"`,
      src: `url('${baseUrl}fabric-icons-14-df06278b.woff') format('woff')`
    },
    icons: {
      'PageListFilter': '\uF813',
      'PageListMirroredSolid': '\uF33B',
      'PageListSolid': '\uF33A',
      'PageLock': '\uF43F',
      'PagePermission': '\uE618',
      'PageRemove': '\uEFBA',
      'PageRight': '\uE761',
      'PageShared': '\uF02D',
      'PageSolid': '\uE729',
      'PanoIndicator': '\uE7B0',
      'Parachute': '\uF351',
      'ParachuteSolid': '\uF352',
      'Parameter': '\uF306',
      'ParkingLocation': '\uE811',
      'ParkingLocationMirrored': '\uEA5E',
      'ParkingMirroredSolid': '\uF34B',
      'ParkingSolid': '\uF34A',
      'PartlyClearNight': '\uE477',
      'PartlyCloudyDay': '\uE9C0',
      'PartlyCloudyNight': '\uE9C1',
      'PartlySunnyDay': '\uE469',
      'PartlySunnyFlurriesDay': '\uE472',
      'PartlySunnyShowersDay': '\uE46E',
      'PartlySunnyShowersNight': '\uE47A',
      'PartlySunnyTStormsDay': '\uE470',
      'PartlySunnyTStormsNight': '\uE47C',
      'PartyLeader': '\uECA7',
      'PassiveAuthentication': '\uF32A',
      'PasswordField': '\uF6AA',
      'Paste': '\uE77F',
      'PasteAsCode': '\uF5D6',
      'PasteAsText': '\uF5D5',
      'Pause': '\uE769',
      'PaymentCard': '\uE8C7',
      'PBIAnomaliesMarker': '\uE554',
      'PBIAnomaly': '\uE548',
      'PBIColumn': '\uE67A',
      'PBIConnectPoints': '\uE67B',
      'PBIDirectQuery': '\uE4E9',
      'PBIDual': '\uE4EA',
      'PBIGap': '\uE67C',
      'PBIGoalEntry': '\uE615',
      'PBIGoalEntryAdd': '\uE616',
      'PBIHomeLayoutDefault': '\uE65B',
      'PBIHomeLayoutExpanded': '\uE65C',
      'PBIImport': '\uE4EB',
      'PBILiveConnect': '\uE4EC',
      'PBIPerspective': '\uE658',
      'PBIReportTemplate': '\uE5EC',
      'PBIZero': '\uE67D',
      'PC1': '\uE977',
      'PDF': '\uEA90',
      'PencilReply': '\uEF7B',
      'Pentagon': '\uF4FF',
      'PenWorkspace': '\uEDC6',
      'People': '\uE716',
      'PeopleAdd': '\uEA15',
      'PeopleAlert': '\uED93',
      'PeopleBlock': '\uED91',
      'PeopleExternalShare': '\uE5EF',
      'PeoplePause': '\uED94',
      'PeopleRepeat': '\uED92',
      'PeopleSettings': '\uF72C',
      'Permissions': '\uE8D7',
      'PermissionsSolid': '\uF349',
      'Personalize': '\uE771',
      'Phishing': '\uF679',
      'PhishingCampaign': '\uE48D',
      'PhishingHook': '\uE48E',
      'Phone': '\uE717',
      'Photo': '\uE91B',
      'Photo2': '\uEB9F',
      'Photo2Add': '\uECAB',
      'Photo2Fill': '\uF79F',
      'Photo2Remove': '\uECAC',
      'PhotoBlock': '\uE4C3',
      'PhotoCollection': '\uE7AA',
      'PhotoError': '\uE3F7',
      'PhotoVideoMedia': '\uF0B1',
      'Picture': '\uE8B9',
      'PictureCenter': '\uF522',
      'PictureFill': '\uF523',
      'PictureLibrary': '\uEEC2',
      'PicturePosition': '\uF524',
      'PictureStretch': '\uF525',
      'PictureTile': '\uF526',
      'PieDouble': '\uEB04',
      'PieSingle': '\uEB05',
      'PieSingleSolid': '\uF530',
      'Pill': '\uEACB',
      'Pin': '\uE718',
      'PinNavMenu': '\uE682',
      'Pinned': '\uE840',
      'PinnedFill': '\uE842',
      'PinnedSolid': '\uF676',
      'PinOff': '\uE683',
      'PinOffSolid': '\uE694',
      'PinSolid': '\uF1DB',
      'PinSolid12': '\uE352',
      'PinSolidOff12': '\uE353'
    }
  };

  registerIcons(subset, options);
}
