  // Your use of the content in the files referenced here is subject to the terms of the license at https://aka.ms/fabric-assets-license

// tslint:disable:max-line-length

import {
  IIconOptions,
  IIconSubset,
  registerIcons
} from '@uifabric/styling';

export function initializeIcons(
  baseUrl: string = '',
  options?: IIconOptions
): void {
  const subset: IIconSubset = {
    style: {
      MozOsxFontSmoothing: 'grayscale',
      WebkitFontSmoothing: 'antialiased',
      fontStyle: 'normal',
      fontWeight: 'normal',
      speak: 'none'
    },
    fontFace: {
      fontFamily: `"FabricMDL2Icons-2"`,
      src: `url('${baseUrl}fabric-icons-2-abd98bc6.woff') format('woff')`
    },
    icons: {
      'BoxAdditionSolid': '\uF2D4',
      'BoxCheckmarkSolid': '\uF2D7',
      'BoxMultiplySolid': '\uF2D5',
      'BoxPlaySolid': '\uF2D6',
      'BoxSubtractSolid': '\uF2D3',
      'BranchCommit': '\uF293',
      'BranchCompare': '\uF294',
      'BranchFork': '\uF173',
      'BranchFork2': '\uF291',
      'BranchLocked': '\uF292',
      'BranchMerge': '\uF295',
      'BranchPullRequest': '\uF296',
      'BranchSearch': '\uF297',
      'BranchShelveset': '\uF298',
      'Breadcrumb': '\uEF8C',
      'Breakfast': '\uF49C',
      'BreakpointsRemove': '\uE692',
      'Brightness': '\uE706',
      'Broom': '\uEA99',
      'BrowserScreenShot': '\uEBED',
      'BrowserTab': '\uF5D7',
      'BrowserTabScreenshot': '\uF5D8',
      'Brunch': '\uF49D',
      'Brush': '\uECFF',
      'BucketColor': '\uF1B6',
      'BucketColorFill': '\uF1B7',
      'BufferTimeAfter': '\uF0D0',
      'BufferTimeBefore': '\uF0CF',
      'BufferTimeBoth': '\uF0D1',
      'Bug': '\uEBE8',
      'BugAction': '\uE358',
      'BugBlock': '\uE400',
      'BugSolid': '\uF335',
      'BugSync': '\uE3FF',
      'BugWarning': '\uE357',
      'Build': '\uF28F',
      'BuildDefinition': '\uF6E9',
      'BuildIssue': '\uF319',
      'BuildQueue': '\uF24F',
      'BuildQueueNew': '\uF250',
      'BulkPageBlock': '\uE553',
      'BulkUpload': '\uF548',
      'BulletedList': '\uE8FD',
      'BulletedList2': '\uF2C7',
      'BulletedList2Mirrored': '\uF2C8',
      'BulletedListBullet': '\uF793',
      'BulletedListBulletMirrored': '\uF795',
      'BulletedListMirrored': '\uEA42',
      'BulletedListText': '\uF792',
      'BulletedListTextMirrored': '\uF794',
      'BulletedTreeList': '\uF84C',
      'Bullseye': '\uF272',
      'BullseyeTarget': '\uF5F0',
      'BullseyeTargetAdd': '\uE664',
      'BullseyeTargetDelete': '\uF6C1',
      'BullseyeTargetEdit': '\uE319',
      'Bus': '\uE806',
      'BusinessCard': '\uE5FB',
      'BusinessCenterLogo': '\uF4B2',
      'BusinessHoursSign': '\uF310',
      'BusinessRule': '\uE562',
      'BusSolid': '\uEB47',
      'ButtonControl': '\uF6C0',
      'Cafe': '\uEC32',
      'Cake': '\uECA4',
      'CalculatedTable': '\uE4BE',
      'Calculator': '\uE8EF',
      'CalculatorAddition': '\uE948',
      'CalculatorDelta': '\uE406',
      'CalculatorEqualTo': '\uE94E',
      'CalculatorGroup': '\uE462',
      'CalculatorMultiply': '\uE947',
      'CalculatorNotEqualTo': '\uF2D2',
      'CalculatorPercentage': '\uE94C',
      'CalculatorSubtract': '\uE949',
      'Calendar': '\uE787',
      'CalendarAgenda': '\uEE9A',
      'CalendarDay': '\uE8BF',
      'CalendarMirrored': '\uED28',
      'CalendarReply': '\uE8F5',
      'CalendarSettings': '\uF558',
      'CalendarSettingsMirrored': '\uF559',
      'CalendarWeek': '\uE8C0',
      'CalendarWorkWeek': '\uEF51',
      'CalendarYear': '\uE371',
      'Calories': '\uECAD',
      'CaloriesAdd': '\uF172',
      'Camera': '\uE722',
      'CampaignTemplate': '\uF811',
      'Cancel': '\uE711',
      'CannedChat': '\uF0F2',
      'CanvasAppTemplate32': '\uE5FE',
      'Car': '\uE804',
      'CareActivity': '\uE549',
      'CarePlan': '\uE54A',
      'CarePlanTemplate': '\uE61E',
      'CaretBottomLeftCenter8': '\uF365',
      'CaretBottomLeftSolid8': '\uF121',
      'CaretBottomRightCenter8': '\uF364',
      'CaretBottomRightSolid8': '\uF122'
    }
  };

  registerIcons(subset, options);
}
