  // Your use of the content in the files referenced here is subject to the terms of the license at https://aka.ms/fabric-assets-license

// tslint:disable:max-line-length

import {
  IIconOptions,
  IIconSubset,
  registerIcons
} from '@uifabric/styling';

export function initializeIcons(
  baseUrl: string = '',
  options?: IIconOptions
): void {
  const subset: IIconSubset = {
    style: {
      MozOsxFontSmoothing: 'grayscale',
      WebkitFontSmoothing: 'antialiased',
      fontStyle: 'normal',
      fontWeight: 'normal',
      speak: 'none'
    },
    fontFace: {
      fontFamily: `"FabricMDL2Icons-16"`,
      src: `url('${baseUrl}fabric-icons-16-974108bf.woff') format('woff')`
    },
    icons: {
      'PythonLanguage': '\uF2F8',
      'QandA': '\uF8A2',
      'QandAMirror': '\uF8A3',
      'QRCode': '\uED14',
      'QuadColumn': '\uF66F',
      'Quantity': '\uE9F8',
      'QuarterCircle': '\uF502',
      'QueryList': '\uF2B8',
      'Questionnaire': '\uEE19',
      'QuestionnaireMirrored': '\uEE4B',
      'QueueAdvanced': '\uE62E',
      'QuickNote': '\uE70B',
      'QuickNoteSolid': '\uF338',
      'Quotes': '\uF067',
      'R': '\uF4EB',
      'RadioBtnOff': '\uECCA',
      'RadioBtnOn': '\uECCB',
      'RadioBullet': '\uE915',
      'Rain': '\uE9C4',
      'RainShowersDay': '\uE9C3',
      'RainShowersNight': '\uEA0F',
      'RainSnow': '\uE9C7',
      'Rate': '\uEB07',
      'RawSource': '\uF299',
      'Read': '\uE8C3',
      'ReadingMode': '\uE736',
      'ReadingModeSolid': '\uF33D',
      'ReadOutLoud': '\uF112',
      'RealEstate': '\uE758',
      'ReceiptCheck': '\uEF5B',
      'ReceiptForward': '\uEF59',
      'ReceiptProcessing': '\uE496',
      'ReceiptReply': '\uEF5A',
      'ReceiptTentative': '\uF41A',
      'ReceiptTentativeMirrored': '\uF41B',
      'ReceiptUndelivered': '\uF419',
      'Recent': '\uE823',
      'Record2': '\uEA3F',
      'RecordRouting': '\uE62D',
      'RecruitmentManagement': '\uEE12',
      'RectangleShape': '\uF1A9',
      'RectangleShapeSolid': '\uF640',
      'RectangularClipping': '\uF407',
      'RecurringEvent': '\uEF5D',
      'RecurringTask': '\uEDB2',
      'RecycleBin': '\uEF87',
      'Redeploy': '\uF29E',
      'RedEye': '\uE7B3',
      'RedEye12': '\uE3AD',
      'Redo': '\uE7A6',
      'Refresh': '\uE72C',
      'RegistryEditor': '\uF1FF',
      'Relationship': '\uF003',
      'ReleaseDefinition': '\uF6EA',
      'ReleaseGate': '\uF7BE',
      'ReleaseGateCheck': '\uF7BF',
      'ReleaseGateError': '\uF7C0',
      'ReminderGroup': '\uEBF8',
      'ReminderPerson': '\uEBF7',
      'ReminderTime': '\uEBF9',
      'Remote': '\uE8AF',
      'RemoteApplication': '\uF621',
      'Remove': '\uE738',
      'RemoveContent': '\uECC7',
      'RemoveEvent': '\uED8A',
      'RemoveFilter': '\uEB08',
      'RemoveFrom': '\uECC9',
      'RemoveFromShoppingList': '\uF7D5',
      'RemoveFromTrash': '\uF82B',
      'RemoveLink': '\uED90',
      'RemoveLinkChain': '\uF79A',
      'RemoveLinkX': '\uF79B',
      'RemoveOccurrence': '\uED9B',
      'Rename': '\uE8AC',
      'RenewalCurrent': '\uF545',
      'RenewalFuture': '\uF546',
      'ReopenPages': '\uED50',
      'Repair': '\uE90F',
      'RepeatAll': '\uE8EE',
      'RepeatHeaderRows': '\uE3EB',
      'RepeatOne': '\uE8ED',
      'Reply': '\uE97A',
      'ReplyAll': '\uEE0A',
      'ReplyAllAlt': '\uEF5F',
      'ReplyAllMirrored': '\uEE36',
      'ReplyAlt': '\uEF5E',
      'ReplyMirrored': '\uEE35',
      'Repo': '\uF2CB',
      'ReportAdd': '\uF52C',
      'ReportAlert': '\uF721',
      'ReportAlertMirrored': '\uF722',
      'ReportDocument': '\uE9F9',
      'ReportHacked': '\uE730',
      'ReportLibrary': '\uEEBB',
      'ReportLibraryMirrored': '\uEEBC',
      'ReportLock': '\uF875',
      'ReportTrophy': '\uE614',
      'ReportWarning': '\uF569',
      'RepoSolid': '\uF2CC',
      'Rerun': '\uF8A1'
    }
  };

  registerIcons(subset, options);
}
