  // Your use of the content in the files referenced here is subject to the terms of the license at https://aka.ms/fabric-assets-license

// tslint:disable:max-line-length

import {
  IIconOptions,
  IIconSubset,
  registerIcons
} from '@uifabric/styling';

export function initializeIcons(
  baseUrl: string = '',
  options?: IIconOptions
): void {
  const subset: IIconSubset = {
    style: {
      MozOsxFontSmoothing: 'grayscale',
      WebkitFontSmoothing: 'antialiased',
      fontStyle: 'normal',
      fontWeight: 'normal',
      speak: 'none'
    },
    fontFace: {
      fontFamily: `"FabricMDL2Icons-18"`,
      src: `url('${baseUrl}fabric-icons-18-701fed0c.woff') format('woff')`
    },
    icons: {
      'SettingsSecure': '\uE4D2',
      'SettingsSync': '\uE359',
      'ShakeDevice': '\uF80A',
      'Shapes': '\uEC7C',
      'ShapeSolid': '\uE422',
      'Share': '\uE72D',
      'SharedDatabase': '\uE3D9',
      'SharedNotes': '\uF481',
      'ShareiOS': '\uEF79',
      'Sharepoint2013LogoInverse': '\uE480',
      'SharepointAppIcon16': '\uE365',
      'SharepointLogo': '\uF27E',
      'SharepointLogoInverse': '\uED18',
      'Shield': '\uEA18',
      'ShieldAlert': '\uF7D7',
      'ShieldSolid': '\uF340',
      'Shirt': '\uED00',
      'Shop': '\uE719',
      'ShopBrand': '\uF478',
      'ShoppingCart': '\uE7BF',
      'ShoppingCartSolid': '\uF342',
      'ShopServer': '\uF2B6',
      'Showers': '\uE46C',
      'ShowGrid': '\uF7DE',
      'ShowResults': '\uE8BC',
      'ShowResultsMirrored': '\uEA65',
      'ShowTimeAs': '\uF787',
      'ShowVisualFilter': '\uF4DE',
      'SidePanel': '\uEF52',
      'SidePanelMirrored': '\uF221',
      'Signin': '\uF286',
      'SignOut': '\uF3B1',
      'SimplifiedView': '\uE5C1',
      'SingleBookmark': '\uEDFF',
      'SingleBookmarkSolid': '\uEE00',
      'SingleColumn': '\uF1D3',
      'SingleColumnEdit': '\uF321',
      'SIPMove': '\uE759',
      'SiteScan': '\uEBEC',
      'SizeLegacy': '\uE2B2',
      'SkipBack10': '\uED3C',
      'SkipForward30': '\uED3D',
      'SkiResorts': '\uEB45',
      'SkypeArrow': '\uF748',
      'SkypeCheck': '\uEF80',
      'SkypeCircleArrow': '\uF747',
      'SkypeCircleCheck': '\uEF7D',
      'SkypeCircleClock': '\uEF7E',
      'SkypeCircleMinus': '\uEF7F',
      'SkypeCircleSlash': '\uF825',
      'SkypeClock': '\uEF81',
      'SkypeForBusinessLogo': '\uF0FC',
      'SkypeForBusinessLogo16': '\uF40F',
      'SkypeForBusinessLogoFill': '\uF27D',
      'SkypeForBusinessLogoFill16': '\uF410',
      'SkypeLogo': '\uEB6F',
      'SkypeLogo16': '\uF40E',
      'SkypeMessage': '\uEF83',
      'SkypeMinus': '\uEF82',
      'SkypeSlash': '\uF826',
      'Sleet': '\uE474',
      'Slider': '\uF527',
      'SliderHandleSize': '\uF528',
      'SliderThumb': '\uEC13',
      'Slideshow': '\uE786',
      'SmartGlassRemote': '\uF80B',
      'SnapToGrid': '\uF7E4',
      'Snooze': '\uF4BD',
      'Snow': '\uE9C8',
      'Snowflake': '\uEB46',
      'SnowShowerDay': '\uE9FD',
      'SnowShowerNight': '\uEA11',
      'Soccer': '\uEB21',
      'SocialListeningLogo': '\uED7C',
      'Sort': '\uE8CB',
      'SortDown': '\uEE69',
      'SortLines': '\uE9D0',
      'SortLinesAscending': '\uE43A',
      'SortUp': '\uEE68',
      'Source': '\uEB1B',
      'Spacer': '\uF40D',
      'Speakers': '\uE7F5',
      'SpecialEvent': '\uF536',
      'Speech': '\uEFA9',
      'SpeechOff': '\uF8BA',
      'SpeedHigh': '\uEC4A',
      'Spelling': '\uF87B',
      'Split': '\uEDBC',
      'SplitObject': '\uF547',
      'Sprint': '\uF3B0',
      'SQLAnalyticsPool': '\uE434',
      'SQLServerLogo': '\uE61A',
      'Squalls': '\uE9CC',
      'SquareShape': '\uF1A6',
      'SquareShapeSolid': '\uF63D',
      'SSLCertificate': '\uF4CB',
      'Stack': '\uF26F',
      'StackColumnChart': '\uE9FC',
      'StackedBarChart': '\uF24D',
      'StackedBarChartFull': '\uF668'
    }
  };

  registerIcons(subset, options);
}
