  // Your use of the content in the files referenced here is subject to the terms of the license at https://aka.ms/fabric-assets-license

// tslint:disable:max-line-length

import {
  IIconOptions,
  IIconSubset,
  registerIcons
} from '@uifabric/styling';

export function initializeIcons(
  baseUrl: string = '',
  options?: IIconOptions
): void {
  const subset: IIconSubset = {
    style: {
      MozOsxFontSmoothing: 'grayscale',
      WebkitFontSmoothing: 'antialiased',
      fontStyle: 'normal',
      fontWeight: 'normal',
      speak: 'none'
    },
    fontFace: {
      fontFamily: `"FabricMDL2Icons-15"`,
      src: `url('${baseUrl}fabric-icons-15-c816b3df.woff') format('woff')`
    },
    icons: {
      'PinToTab': '\uE5E5',
      'PivotChart': '\uF24C',
      'PlainText': '\uF834',
      'PlannerLogo': '\uEDD1',
      'PlanView': '\uF360',
      'Play': '\uE768',
      'PlaybackRate1x': '\uEC57',
      'PlayerSettings': '\uEF58',
      'PlaylistMusic': '\uE93F',
      'PlayResume': '\uF2C6',
      'PlayReverse': '\uF3E5',
      'PlayReverseResume': '\uF3E4',
      'PlaySolid': '\uF5B0',
      'Plug': '\uF300',
      'PlugConnected': '\uF302',
      'PlugDisconnected': '\uF303',
      'PlugSolid': '\uF301',
      'POI': '\uECAF',
      'POISolid': '\uF2D1',
      'PollResults': '\uF8A0',
      'PopExpand': '\uE49A',
      'PortalAppTemplate32': '\uE5FC',
      'PostUpdate': '\uE8F3',
      'PowerApps': '\uEDD2',
      'PowerApps2Logo': '\uF092',
      'PowerAppsLogo': '\uF091',
      'PowerAppsTemplate': '\uE4AC',
      'PowerAutomateLogo': '\uF4B1',
      'PowerBILogo': '\uEA1E',
      'PowerBILogo16': '\uF790',
      'PowerBILogoBackplate16': '\uF791',
      'PowerButton': '\uE7E8',
      'PowerPointDocument': '\uEF72',
      'PowerPointLogo': '\uF1EB',
      'PowerPointLogo16': '\uF394',
      'PowerPointLogoInverse': '\uEC2A',
      'PowerPointLogoInverse16': '\uF393',
      'PowerShell': '\uF1FD',
      'PowerShell2': '\uF730',
      'PowerStandby': '\uE55C',
      'PowerVirtualAgentsLogo': '\uE484',
      'Precipitation': '\uE9CF',
      'PresenceChickletVideo': '\uE979',
      'Presentation': '\uF6E4',
      'Presentation12': '\uF6E5',
      'Preview': '\uE8FF',
      'PreviewBelow': '\uE5D5',
      'PreviewLink': '\uE8A1',
      'PreviewSideBySide': '\uE5D6',
      'Previous': '\uE892',
      'PrimaryCalendar': '\uF4AE',
      'Print': '\uE749',
      'PrintfaxPrinterFile': '\uE956',
      'Priority': '\uE8D0',
      'Process': '\uE9F3',
      'ProcessAdvisor': '\uE5E4',
      'Processing': '\uE9F5',
      'ProcessingCancel': '\uE403',
      'ProcessingPause': '\uE405',
      'ProcessingRun': '\uE404',
      'ProcessMap': '\uE9F6',
      'ProcessMetaTask': '\uF290',
      'Product': '\uECDC',
      'ProductCatalog': '\uEFE8',
      'ProductionFloorManagement': '\uEE29',
      'ProductList': '\uE31E',
      'ProductRelease': '\uEE2E',
      'ProductVariant': '\uEE30',
      'ProductWarning': '\uE5C0',
      'ProfileSearch': '\uEF35',
      'ProFootball': '\uEB27',
      'ProgressLoopInner': '\uECDE',
      'ProgressLoopOuter': '\uECDF',
      'ProgressRing5': '\uEDF6',
      'ProgressRingDots': '\uF16A',
      'ProHockey': '\uEB28',
      'ProjectCollection': '\uF363',
      'ProjectDocument': '\uF759',
      'ProjectLogo16': '\uF480',
      'ProjectLogo32': '\uF47E',
      'ProjectLogoInverse': '\uEDD4',
      'ProjectManagement': '\uE9DE',
      'PromotedDatabase': '\uF77D',
      'Pronouns': '\uE556',
      'ProtectedDocument': '\uE8A6',
      'ProtectionCenterLogo32': '\uF494',
      'ProtectRestrict': '\uF22A',
      'ProvisioningPackage': '\uE835',
      'PublicCalendar': '\uEF6D',
      'PublicContactCard': '\uEF6E',
      'PublicContactCardMirrored': '\uF230',
      'PublicEmail': '\uEF6F',
      'PublicFolder': '\uEF70',
      'PublishContent': '\uF0D4',
      'PublishCourse': '\uF699',
      'PublisherLogo': '\uF1ED',
      'PublisherLogo16': '\uF3A0',
      'PublisherLogoInverse16': '\uF39F',
      'Puzzle': '\uEA86',
      'PY': '\uF2F9'
    }
  };

  registerIcons(subset, options);
}
