  // Your use of the content in the files referenced here is subject to the terms of the license at https://aka.ms/fabric-assets-license

// tslint:disable:max-line-length

import {
  IIconOptions,
  IIconSubset,
  registerIcons
} from '@uifabric/styling';

export function initializeIcons(
  baseUrl: string = '',
  options?: IIconOptions
): void {
  const subset: IIconSubset = {
    style: {
      MozOsxFontSmoothing: 'grayscale',
      WebkitFontSmoothing: 'antialiased',
      fontStyle: 'normal',
      fontWeight: 'normal',
      speak: 'none'
    },
    fontFace: {
      fontFamily: `"FabricMDL2Icons-8"`,
      src: `url('${baseUrl}fabric-icons-8-4745398a.woff') format('woff')`
    },
    icons: {
      'ExportMirrored': '\uEDE2',
      'ExpressRouteCircuits': '\uE557',
      'ExternalBuild': '\uF445',
      'ExternalTFVC': '\uF446',
      'ExternalUser': '\uE4CA',
      'ExternalXAML': '\uF447',
      'Eyedropper': '\uEF3C',
      'EyeShadow': '\uF7EB',
      'F12DevTools': '\uEBEE',
      'FabricAssetLibrary': '\uF09C',
      'FabricChannelFolder': '\uE4FA',
      'FabricDataConnectionLibrary': '\uF09D',
      'FabricDocLibrary': '\uF09E',
      'FabricFolder': '\uF0A9',
      'FabricFolderConfirm': '\uF7FF',
      'FabricFolderFill': '\uF0AA',
      'FabricFolderLink': '\uE45C',
      'FabricFolderSearch': '\uF0A4',
      'FabricFolderUpload': '\uE3AC',
      'FabricFormLibrary': '\uF09F',
      'FabricFormLibraryMirrored': '\uF0A0',
      'FabricMovetoFolder': '\uF0A5',
      'FabricNetworkFolder': '\uF5E6',
      'FabricNewFolder': '\uF0AB',
      'FabricOpenFolderHorizontal': '\uF0A8',
      'FabricPictureLibrary': '\uF0AC',
      'FabricPublicFolder': '\uF0A3',
      'FabricReportLibrary': '\uF0A1',
      'FabricReportLibraryMirrored': '\uF0A2',
      'FabricSyncFolder': '\uF0A7',
      'FabricTextHighlight': '\uF79C',
      'FabricTextHighlightComposite': '\uF7DA',
      'FabricUnsyncFolder': '\uF0A6',
      'FabricUserFolder': '\uF5E5',
      'Factory': '\uE60E',
      'Family': '\uEBDA',
      'FangBody': '\uECEB',
      'FastForward': '\uEB9D',
      'FastForwardEightX': '\uE443',
      'FastForwardFourX': '\uE442',
      'FastForwardOneFiveX': '\uE440',
      'FastForwardOneX': '\uE43F',
      'FastForwardPointFiveX': '\uE43E',
      'FastForwardTwoX': '\uE441',
      'FastMode': '\uF19A',
      'Favicon': '\uE737',
      'FavoriteBlock': '\uE67E',
      'FavoriteList': '\uE728',
      'FavoriteStar': '\uE734',
      'FavoriteStarFill': '\uE735',
      'Fax': '\uEF5C',
      'Feedback': '\uED15',
      'FeedbackRequestMirroredSolid': '\uF35A',
      'FeedbackRequestSolid': '\uF359',
      'FeedbackResponseSolid': '\uF35B',
      'Ferry': '\uE7E3',
      'FerrySolid': '\uEB48',
      'FieldChanged': '\uF2C3',
      'FieldEmpty': '\uF2C1',
      'FieldFilled': '\uF2C2',
      'FieldNotChanged': '\uF2C4',
      'FieldReadOnly': '\uF442',
      'FieldRequired': '\uF443',
      'FileASPX': '\uF2E9',
      'FileBug': '\uF30D',
      'FileCode': '\uF30E',
      'FileComment': '\uF30F',
      'FileCSS': '\uF2EA',
      'FileHTML': '\uF2ED',
      'FileImage': '\uF311',
      'FileJAVA': '\uF2E8',
      'FileLess': '\uF2EC',
      'FileOff': '\uE3FC',
      'FilePDB': '\uF2E5',
      'FileRequest': '\uF789',
      'FileSass': '\uF2EB',
      'FileSQL': '\uF2E7',
      'FileSymlink': '\uF312',
      'FileSystem': '\uE433',
      'FileTemplate': '\uF2E6',
      'FileTypeSolution': '\uF387',
      'FileYML': '\uF5DA',
      'Filter': '\uE71C',
      'FilterAscending': '\uF21A',
      'FilterDescending': '\uF21B',
      'Filters': '\uE795',
      'FilterSettings': '\uF76C',
      'FilterSolid': '\uF412',
      'FiltersSolid': '\uF353',
      'Financial': '\uE7BB',
      'FinancialMirroredSolid': '\uF347',
      'FinancialSolid': '\uF346',
      'Fingerprint': '\uE928',
      'FitPage': '\uE9A6',
      'FitWidth': '\uE9A7',
      'FiveTileGrid': '\uF274',
      'FixedAssetManagement': '\uEF93',
      'FixedColumnWidth': '\uE3EA',
      'Flag': '\uE7C1',
      'FlameSolid': '\uF1F3'
    }
  };

  registerIcons(subset, options);
}
