  // Your use of the content in the files referenced here is subject to the terms of the license at https://aka.ms/fabric-assets-license

// tslint:disable:max-line-length

import {
  IIconOptions,
  IIconSubset,
  registerIcons
} from '@uifabric/styling';

export function initializeIcons(
  baseUrl: string = '',
  options?: IIconOptions
): void {
  const subset: IIconSubset = {
    style: {
      MozOsxFontSmoothing: 'grayscale',
      WebkitFontSmoothing: 'antialiased',
      fontStyle: 'normal',
      fontWeight: 'normal',
      speak: 'none'
    },
    fontFace: {
      fontFamily: `"FabricMDL2Icons-20"`,
      src: `url('${baseUrl}fabric-icons-20-c23758d2.woff') format('woff')`
    },
    icons: {
      'TableLastColumn': '\uE3F0',
      'TableLink': '\uF77A',
      'TablePermission': '\uE619',
      'Tablet': '\uE70A',
      'TabletMode': '\uEBFC',
      'TableTotalRow': '\uE3ED',
      'TabletSelected': '\uEC74',
      'TabOneColumn': '\uF849',
      'TabThreeColumn': '\uF84B',
      'TabTwoColumn': '\uF84A',
      'Tag': '\uE8EC',
      'TagGroup': '\uE3F6',
      'TagSolid': '\uF70E',
      'TagUnknown': '\uF6DF',
      'TagUnknown12': '\uF6E1',
      'TagUnknown12Mirror': '\uF6E2',
      'TagUnknownMirror': '\uF6E0',
      'Task': '\uF7EC',
      'TaskAdd': '\uE4FD',
      'Taskboard': '\uF1C2',
      'TaskGroup': '\uF2AE',
      'TaskGroupMirrored': '\uF2AF',
      'TaskList': '\uE3B6',
      'TaskLogo': '\uF493',
      'TaskManager': '\uEDB7',
      'TaskManagerMirrored': '\uEDB8',
      'TaskSolid': '\uF333',
      'Taxi': '\uF4A1',
      'TeamFavorite': '\uF2AD',
      'TeamsLogo': '\uF27B',
      'TeamsLogo16': '\uF40A',
      'TeamsLogoInverse': '\uF27A',
      'Teamwork': '\uEA12',
      'Teeth': '\uF4A0',
      'Telemarketer': '\uE7B9',
      'TemporaryAccessPass': '\uE4AD',
      'TemporaryUser': '\uEE58',
      'Tennis': '\uEB33',
      'TestAdd': '\uE4DC',
      'TestAutoSolid': '\uF3A8',
      'TestBeaker': '\uF3A5',
      'TestBeakerSolid': '\uF3A6',
      'TestCase': '\uF3AF',
      'TestExploreSolid': '\uF3A7',
      'TestImpactSolid': '\uF3AA',
      'TestParameter': '\uF3AD',
      'TestPlan': '\uF3AB',
      'TestRemove': '\uE4E1',
      'TestStep': '\uF3AC',
      'TestSuite': '\uF3AE',
      'TestUserSolid': '\uF3A9',
      'TextAlignBottom': '\uE3E2',
      'TextAlignMiddle': '\uE3E1',
      'TextAlignTop': '\uE3E0',
      'TextBox': '\uEDC2',
      'TextCallout': '\uF2A2',
      'TextDocument': '\uF029',
      'TextDocumentEdit': '\uE43B',
      'TextDocumentSettings': '\uE4AA',
      'TextDocumentShared': '\uF02B',
      'TextField': '\uEDC3',
      'TextOverflow': '\uF51F',
      'TextParagraphOption': '\uE3E3',
      'TextRecognition': '\uE394',
      'TextRotate270Degrees': '\uE3E7',
      'TextRotate90Degrees': '\uE3E6',
      'TextRotateHorizontal': '\uE3E5',
      'TextRotation': '\uE3E4',
      'TFVCLogo': '\uF44D',
      'ThisPC': '\uEC4E',
      'ThreeQuarterCircle': '\uF503',
      'ThumbnailView': '\uE7B6',
      'ThumbnailViewMirrored': '\uEA67',
      'Thunderstorms': '\uE9C6',
      'Ticket': '\uEB54',
      'Tiles': '\uECA5',
      'Tiles2': '\uEF7C',
      'TimeEntry': '\uEF95',
      'TimeEntryTemplate': '\uF635',
      'Timeline': '\uED9C',
      'TimelineDelivery': '\uF2AB',
      'TimelineMatrixView': '\uF361',
      'TimelineProgress': '\uF2AA',
      'TimePicker': '\uE367',
      'Timer': '\uE91E',
      'TimeSheet': '\uEA05',
      'Title': '\uF23B',
      'TitleMirrored': '\uF23C',
      'ToDoLogoBottom': '\uF4B3',
      'ToDoLogoInverse': '\uF4BC',
      'ToDoLogoOutline': '\uF75B',
      'ToDoLogoTop': '\uF4B4',
      'ToggleBorder': '\uEC12',
      'ToggleFilled': '\uEC11',
      'ToggleLeft': '\uF19E',
      'ToggleRight': '\uF19F',
      'ToggleThumb': '\uEC14',
      'Toll': '\uF160',
      'Toolbox': '\uECED',
      'Total': '\uE9DF'
    }
  };

  registerIcons(subset, options);
}
