  // Your use of the content in the files referenced here is subject to the terms of the license at https://aka.ms/fabric-assets-license

// tslint:disable:max-line-length

import {
  IIconOptions,
  IIconSubset,
  registerIcons
} from '@uifabric/styling';

export function initializeIcons(
  baseUrl: string = '',
  options?: IIconOptions
): void {
  const subset: IIconSubset = {
    style: {
      MozOsxFontSmoothing: 'grayscale',
      WebkitFontSmoothing: 'antialiased',
      fontStyle: 'normal',
      fontWeight: 'normal',
      speak: 'none'
    },
    fontFace: {
      fontFamily: `"FabricMDL2Icons-3"`,
      src: `url('${baseUrl}fabric-icons-3-734e02ad.woff') format('woff')`
    },
    icons: {
      'CaretDown8': '\uEDD8',
      'CaretDownSolid8': '\uEDDC',
      'CaretHollow': '\uE817',
      'CaretHollowMirrored': '\uEA45',
      'CaretLeft8': '\uEDD5',
      'CaretLeftSolid8': '\uEDD9',
      'CaretRight': '\uF06B',
      'CaretRight8': '\uEDD6',
      'CaretRightSolid8': '\uEDDA',
      'CaretSolid': '\uE818',
      'CaretSolid16': '\uEE62',
      'CaretSolidAlt': '\uE483',
      'CaretSolidDown': '\uF08E',
      'CaretSolidLeft': '\uF08D',
      'CaretSolidMirrored': '\uEA46',
      'CaretSolidRight': '\uF08F',
      'CaretSolidUp': '\uF090',
      'CaretTopLeftCenter8': '\uF367',
      'CaretTopLeftSolid8': '\uEF54',
      'CaretTopRightCenter8': '\uF366',
      'CaretTopRightSolid8': '\uEF55',
      'CaretUp8': '\uEDD7',
      'CaretUpSolid8': '\uEDDB',
      'CaseSetting': '\uF675',
      'Cat': '\uED7F',
      'CategoryClassification': '\uE48C',
      'CC': '\uE7F0',
      'CCSolid': '\uE4F4',
      'CellPhone': '\uE8EA',
      'CellSplitVertical': '\uE66C',
      'Certificate': '\uEB95',
      'CertifiedDatabase': '\uF5BB',
      'ChangeEntitlements': '\uE310',
      'Chart': '\uE999',
      'CharticulatorArrangePolar': '\uE632',
      'CharticulatorArrangePolarAngles': '\uE633',
      'CharticulatorBand': '\uE634',
      'CharticulatorGuideCoordinator': '\uE635',
      'CharticulatorGuideX': '\uE636',
      'CharticulatorGuideY': '\uE637',
      'CharticulatorLegend': '\uE638',
      'CharticulatorLine': '\uE639',
      'CharticulatorLineStyleDashed': '\uE63A',
      'CharticulatorLineStyleDotted': '\uE63B',
      'CharticulatorLinkingData': '\uE63C',
      'CharticulatorLinkingSequence': '\uE63D',
      'CharticulatorOrderColumn': '\uE63E',
      'CharticulatorOrderRow': '\uE63F',
      'CharticulatorPlotCartesian': '\uE640',
      'CharticulatorPlotCurve': '\uE641',
      'CharticulatorPolarCoordinates': '\uE642',
      'CharticulatorSpiral': '\uE643',
      'CharticulatorStackRadial': '\uE644',
      'CharticulatorStackY': '\uE645',
      'ChartSeries': '\uF513',
      'ChartTemplate': '\uF812',
      'ChartXAngle': '\uF514',
      'ChartYAngle': '\uF515',
      'Chat': '\uE901',
      'ChatBot': '\uF08B',
      'ChatInviteFriend': '\uECFE',
      'ChatSettings': '\uE600',
      'ChatSolid': '\uF344',
      'Checkbox': '\uE739',
      'CheckboxComposite': '\uE73A',
      'CheckboxCompositeReversed': '\uE73D',
      'CheckboxFill': '\uE73B',
      'CheckboxIndeterminate': '\uE73C',
      'CheckboxIndeterminateCombo': '\uF16E',
      'CheckedOutByOther12': '\uF630',
      'CheckedOutByYou12': '\uF631',
      'CheckList': '\uE9D5',
      'CheckListCheck': '\uF7A9',
      'CheckListCheckMirrored': '\uF7AB',
      'CheckListText': '\uF7A8',
      'CheckListTextMirrored': '\uF7AA',
      'CheckMark': '\uE73E',
      'ChevronDown': '\uE70D',
      'ChevronDownEnd': '\uF5E4',
      'ChevronDownEnd6': '\uF36F',
      'ChevronDownMed': '\uE972',
      'ChevronDownSmall': '\uE96E',
      'ChevronFold10': '\uF36A',
      'ChevronLeft': '\uE76B',
      'ChevronLeftEnd6': '\uF371',
      'ChevronLeftMed': '\uE973',
      'ChevronLeftSmall': '\uE96F',
      'ChevronRight': '\uE76C',
      'ChevronRightEnd6': '\uF372',
      'ChevronRightMed': '\uE974',
      'ChevronRightSmall': '\uE970',
      'ChevronUnfold10': '\uF369',
      'ChevronUp': '\uE70E',
      'ChevronUpEnd': '\uE55B',
      'ChevronUpEnd6': '\uF370',
      'ChevronUpMed': '\uE971',
      'ChevronUpSmall': '\uE96D',
      'Childof': '\uF82D',
      'ChoiceColumn': '\uE4AE',
      'Chopsticks': '\uF4A2'
    }
  };

  registerIcons(subset, options);
}
