  // Your use of the content in the files referenced here is subject to the terms of the license at https://aka.ms/fabric-assets-license

// tslint:disable:max-line-length

import {
  IIconOptions,
  IIconSubset,
  registerIcons
} from '@uifabric/styling';

export function initializeIcons(
  baseUrl: string = '',
  options?: IIconOptions
): void {
  const subset: IIconSubset = {
    style: {
      MozOsxFontSmoothing: 'grayscale',
      WebkitFontSmoothing: 'antialiased',
      fontStyle: 'normal',
      fontWeight: 'normal',
      speak: 'none'
    },
    fontFace: {
      fontFamily: `"FabricMDL2Icons-9"`,
      src: `url('${baseUrl}fabric-icons-9-457f2e9a.woff') format('woff')`
    },
    icons: {
      'FlashAuto': '\uE95C',
      'Flashlight': '\uE754',
      'FlashOff': '\uEA6E',
      'FlickDown': '\uE935',
      'FlickLeft': '\uE937',
      'FlickRight': '\uE938',
      'FlickUp': '\uE936',
      'Flow': '\uEF90',
      'FlowChart': '\uE9D4',
      'Flower': '\uF54E',
      'FlowTemplate': '\uE49C',
      'FlowTrigger': '\uE60C',
      'FluidLogo': '\uE48A',
      'FocalPoint': '\uF277',
      'Focus': '\uEA6F',
      'FocusView': '\uF1A3',
      'Fog': '\uE9CB',
      'Folder': '\uE8B7',
      'FolderFill': '\uE8D5',
      'FolderHorizontal': '\uF12B',
      'FolderList': '\uF2CE',
      'FolderListMirrored': '\uF2CF',
      'FolderOpen': '\uE838',
      'FolderQuery': '\uF2CD',
      'FolderSearch': '\uEF65',
      'FollowUser': '\uEE05',
      'Font': '\uE8D2',
      'FontColor': '\uE8D3',
      'FontColorA': '\uF4EC',
      'FontColorKorean': '\uE5BE',
      'FontColorSwatch': '\uF4ED',
      'FontDecrease': '\uE8E7',
      'FontIncrease': '\uE8E8',
      'FontSize': '\uE8E9',
      'FontSize2': '\uE3C0',
      'FontStyleKorean': '\uE5BA',
      'Footer': '\uF82E',
      'FormatPainter': '\uE3DC',
      'FormLibrary': '\uEEB9',
      'FormLibraryMirrored': '\uEEBA',
      'FormProcessing': '\uE48B',
      'Forum': '\uE378',
      'Forward': '\uE72A',
      'ForwardEvent': '\uED8C',
      'Freezing': '\uE9EF',
      'FreezingRain': '\uE475',
      'Frigid': '\uE9CA',
      'FrontCamera': '\uE96B',
      'FSharp': '\uF2F6',
      'FSharpLanguage': '\uF2F5',
      'FullCircleMask': '\uE91F',
      'FullHistory': '\uF31C',
      'FullScreen': '\uE740',
      'FullView': '\uF1A2',
      'FullWidth': '\uF2FE',
      'FullWidthEdit': '\uF2FF',
      'FunctionalManagerDashboard': '\uF542',
      'FunnelChart': '\uE9F1',
      'GallatinLogo': '\uF496',
      'Game': '\uE7FC',
      'Gather': '\uE460',
      'Generate': '\uE9DA',
      'GenericScan': '\uEE6F',
      'GenericScanFilled': '\uF7E3',
      'GIF': '\uF4A9',
      'Giftbox': '\uEC1F',
      'GiftboxOpen': '\uF133',
      'GiftBoxSolid': '\uF341',
      'GiftCard': '\uEB8E',
      'GitGraph': '\uF2CA',
      'Glasses': '\uEA16',
      'Glimmer': '\uECF4',
      'GlobalNavButton': '\uE700',
      'GlobalNavButtonActive': '\uF89F',
      'Globe': '\uE774',
      'Globe2': '\uF49A',
      'GlobeFavorite': '\uEF53',
      'Go': '\uE8AD',
      'Golf': '\uEB1F',
      'GoMirrored': '\uEA4F',
      'GoToDashboard': '\uEEED',
      'GotoToday': '\uE8D1',
      'GraphSymbol': '\uE35D',
      'GreetingCard': '\uF54B',
      'GridViewLarge': '\uF234',
      'GridViewMedium': '\uF233',
      'GridViewSmall': '\uF232',
      'GripperBarHorizontal': '\uE76F',
      'GripperBarVertical': '\uE784',
      'GripperDotsVertical': '\uF772',
      'GripperTool': '\uE75E',
      'Group': '\uE902',
      'GroupedAscending': '\uEE67',
      'GroupedDescending': '\uEE66',
      'GroupedList': '\uEF74',
      'GroupList': '\uF168',
      'GroupObject': '\uF4F1',
      'GroupRemove': '\uE495',
      'GUID': '\uF52B',
      'Guitar': '\uF49B'
    }
  };

  registerIcons(subset, options);
}
