  // Your use of the content in the files referenced here is subject to the terms of the license at https://aka.ms/fabric-assets-license

// tslint:disable:max-line-length

import {
  IIconOptions,
  IIconSubset,
  registerIcons
} from '@uifabric/styling';

export function initializeIcons(
  baseUrl: string = '',
  options?: IIconOptions
): void {
  const subset: IIconSubset = {
    style: {
      MozOsxFontSmoothing: 'grayscale',
      WebkitFontSmoothing: 'antialiased',
      fontStyle: 'normal',
      fontWeight: 'normal',
      speak: 'none'
    },
    fontFace: {
      fontFamily: `"FabricMDL2Icons-5"`,
      src: `url('${baseUrl}fabric-icons-5-accd4f4b.woff') format('woff')`
    },
    icons: {
      'CommentUrgent': '\uF307',
      'Commitments': '\uEC4D',
      'CommonDataServiceCDS': '\uE377',
      'CommunicationDetails': '\uE4CF',
      'CommunicationDetailsMirrored': '\uE4D0',
      'Communications': '\uE95A',
      'CompactColumnList': '\uF1EE',
      'CompactViewList': '\uF1EA',
      'CompanyDirectory': '\uEF0D',
      'CompanyDirectoryMirrored': '\uEF2B',
      'Compare': '\uF057',
      'CompareUneven': '\uE42E',
      'CompassNW': '\uE942',
      'Completed': '\uE930',
      'Completed12': '\uE559',
      'CompletedSolid': '\uEC61',
      'ComplianceAudit': '\uE369',
      'ConfigurationSolid': '\uF334',
      'ConfirmEvent': '\uE680',
      'ConnectContacts': '\uEFD4',
      'ConnectVirtualMachine': '\uEE9D',
      'ConstructionCone': '\uE98F',
      'ConstructionConeSolid': '\uF339',
      'Contact': '\uE77B',
      'ContactCard': '\uEEBD',
      'ContactCardSettings': '\uF556',
      'ContactCardSettingsMirrored': '\uF557',
      'ContactHeart': '\uF862',
      'ContactInfo': '\uE779',
      'ContactInfoMirrored': '\uEA4A',
      'ContactLink': '\uF25F',
      'ContactList': '\uF7E5',
      'ContactLock': '\uF400',
      'ContentFeed': '\uE428',
      'ContentSettings': '\uF647',
      'ContentUnderstandingApp': '\uE4FB',
      'ContextMenu': '\uF37C',
      'Contrast': '\uE7A1',
      'Copy': '\uE8C8',
      'CopyEdit': '\uE464',
      'CopyPath': '\uE62F',
      'CortanaLogoBeckonInner': '\uF4C6',
      'CortanaLogoBeckonOuter': '\uF4C7',
      'CortanaLogoInner': '\uE832',
      'CortanaLogoOuter': '\uE831',
      'CortanaLogoReadyInner': '\uF4C8',
      'CortanaLogoReadyOuter': '\uF4C9',
      'CostContralLedgerAdmin': '\uF208',
      'CostControl': '\uF207',
      'Cotton': '\uEAF3',
      'Count': '\uE9EE',
      'Coupon': '\uF7BC',
      'CPlusPlus': '\uF2F4',
      'CPlusPlusLanguage': '\uF2F3',
      'CreateMailRule': '\uF67A',
      'CreditCardBill': '\uECD6',
      'Cricket': '\uEB1E',
      'CriticalErrorSolid': '\uF5C9',
      'CRMLead': '\uEFD6',
      'CRMProcesses': '\uEFB1',
      'CRMReport': '\uEFFE',
      'CRMResourceOptimizationApp32': '\uF6EF',
      'CRMServices': '\uEFD2',
      'Crop': '\uE7A8',
      'Crown': '\uED01',
      'CrownSolid': '\uF336',
      'CSharp': '\uF2F0',
      'CSharpLanguage': '\uF2EF',
      'CSS': '\uEBEF',
      'CtrlButton': '\uE4B8',
      'CubeShape': '\uF1AA',
      'CubeShapeSolid': '\uE421',
      'Currency': '\uEAF5',
      'CustomActivity': '\uEFF0',
      'CustomEntity': '\uEFF7',
      'CustomerAssets': '\uF426',
      'CustomizeToolbar': '\uF828',
      'CustomList': '\uEEBE',
      'CustomListMirrored': '\uEEBF',
      'Cut': '\uE8C6',
      'Cycling': '\uEAC7',
      'D365BusinessCentral': '\uF833',
      'D365CoreHR': '\uF6BD',
      'D365CustomerInsights': '\uF3C8',
      'D365CustomerVoiceApp': '\uE4F7',
      'D365ProjectOperations': '\uE432',
      'D365TalentInsight': '\uF6BC',
      'D365TalentLearn': '\uF6BB',
      'DashboardAdd': '\uF52D',
      'DataAnalysis': '\uF731',
      'Database': '\uEFC7',
      'DatabaseActivity': '\uE670',
      'DatabaseBlock': '\uE617',
      'DatabaseRefresh': '\uE67F',
      'DatabaseSource': '\uE30A',
      'DatabaseSwap': '\uE671',
      'DatabaseSync': '\uF842',
      'DatabaseView': '\uE437',
      'DataConnectionLibrary': '\uEEB7',
      'DataEnrichment': '\uE4F5'
    }
  };

  registerIcons(subset, options);
}
