//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHUNetMVC.Abstraction.Model.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_PHE_ADSEntities : DbContext
    {
        public DB_PHE_ADSEntities()
            : base("name=DB_PHE_ADSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Departement> Departements { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<EmployeeEducation> EmployeeEducations { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<Region> Regions { get; set; }
        public virtual DbSet<Territory> Territories { get; set; }
        public virtual DbSet<Worker> Workers { get; set; }
        public virtual DbSet<MD_Aset> MD_Aset { get; set; }
        public virtual DbSet<MD_Location> MD_Location { get; set; }
        public virtual DbSet<TR_History> TR_History { get; set; }
        public virtual DbSet<TR_HistoryFoto> TR_HistoryFoto { get; set; }
    }
}
