//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHUNetMVC.Abstraction.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MD_Aset
    {
        public string AsetNo { get; set; }
        public Nullable<int> LineNo { get; set; }
        public Nullable<int> LocationId { get; set; }
        public string NomorAsetMySAP { get; set; }
        public string MySAPLineNo { get; set; }
        public string HarmoniNo { get; set; }
        public string SinasNo { get; set; }
        public string Deskripsi { get; set; }
        public string Merk { get; set; }
        public string KategoriAset { get; set; }
        public Nullable<int> TahunPerolehan { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string StatusPenggunaan { get; set; }
        public Nullable<int> Level { get; set; }
        public Nullable<int> KondisiAset { get; set; }
        public string LokasiAset { get; set; }
        public string PathFotoTagging { get; set; }
        public string PathFotoKeseluruhan { get; set; }
    }
}
