//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHUNetMVC.Abstraction.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_History
    {
        public int HistoryId { get; set; }
        public Nullable<System.DateTime> TanggalUpdate { get; set; }
        public string Description { get; set; }
        public string KategoriAset { get; set; }
        public string KondisiAset { get; set; }
        public Nullable<int> UserName { get; set; }
        public string AsetNo { get; set; }
    }
}
