//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHUNetMVC.Abstraction.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_HistoryFoto
    {
        public int HistoryFotoId { get; set; }
        public Nullable<int> HistoryId { get; set; }
        public string NamaFoto { get; set; }
        public string PathFotoTagging { get; set; }
        public string PathFotoKeseluruhan { get; set; }
    }
}
